### ISSUE TITLE
Controlling clonality / ploidy in CNVCall

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#10]
Hi Christoffer,

I have a sample which has very low purity (WS9-T in the figure below). When I run superFreq it predicts that it has very high ploidy, which I know isn't likely because a sample from the same tumor at a different time (WS9-C) shows a different ploidy profile.

Can I control the CNACall procedure?
![cnvcall](https://user-images.githubusercontent.com/25452585/28108083-f6a8d908-66f2-11e7-84e9-3624e29b8940.PNG)

**Comment by ChristofferFlensburg** [comment]
It's not well supported at all, but I did add a backdoor to do that manually. You need to set the global variable ".doSuperFreqPloidyManually" to TRUE, and it'll enter manual ploidy for each sample during the run. You will be prompted to type things into the terminal as it runs. You need to rerun with forceRedo = forceRedoCNV = T as well. I only used it once or twice, and I wasn't really happy with how it worked. I also haven't used it for several versions, so may not work at all any more... :/

Ideally it'd give the best few solutions and let you choose between those, or even select solutions based also on the other samples, but that is far into the future.

Another approach here is to increase systematicVariance, as it seems like the uncertainties in the x-axis are a bit low. compared to the spread. This is particularly visible in the second plot, but probably affects the low purity sample as well.

**Comment by gilhornung** [comment]
Thanks for the fast reply!

I've tried .doSuperFreqPloidyManually = T option. Good news are that it is not not broken (I think it is a nice option that you should keep). Bad news are that I probably over-corrected (see image below)... Can you explain a little bit on the process of manual ploidy selection?

First, I understand that I need to choose an index with a low inconsistency score from the plot on the right. Indeed, I saw two troughs at similar depths, and I chose the one which is not automatically selected. But then there was a recalculation and I had to choose an index again and again. Why? 

Second, how are the plots on the left related to the inconsistency score plot?

![cnvcall_2](https://user-images.githubusercontent.com/25452585/28116203-c1bd962a-6710-11e7-9625-2f1ba45b58a3.PNG)

-----------------

Just for reference (if someone looks at this post), to force redo the CNV calling step here is the code I used:
```
forceRedo = forceRedoNothing()
forceRedo$forceRedoCNV = T
```

**Comment by gilhornung** [comment]
Hi Christoffer, 

I increased the systematicVariance to 0.06 and got a great result!

Thanks!

![cnvcall_3](https://user-images.githubusercontent.com/25452585/28118749-fe2211a4-671a-11e7-862e-9de0adbba3e2.PNG)

**Comment by ChristofferFlensburg** [comment]
I think there was a bug in the manual poidy estimate. Seems like part was hard-coded for 20 indices to choose between, while I at some point must have changed the default to 100... Which mean that it your ploidy got pushed down a fair bit when you exit. I did a super quick fix that may fix it (completely untested), so try to update and run if you feel like.

Otherwise the higher variance is probably the more publishable approach here. :)

**Comment by gilhornung** [comment]
I'll stick to the higher variance because it worked well (and is easier to explain).
Thanks!

**Comment by andrewrech** [comment]
Thank you both for documenting this, it helped me find a solution quickly.

@ChristofferFlensburg any thoughts as to whether this method of manually setting ploidy has been maintained? I may want to PR this if not.

**Comment by ChristofferFlensburg** [comment]
Hi! Sorry, I missed this!

I haven't touched it, so it's still in the code. I haven't touched the ploidy estimates in a while, so it may even work, but it's really not user friendly. You need to run it in an interactive terminal and type in numbers into the console to pick the local max to the fitness function (or it might be a local minimum to the disagreement function, RMS of Z-scores or something like that).

I don't have much time to spend on this, but I am happy to do some support if you want to look into this closer and if you can build something that is a bit more user friendly, then a PR would be awesome!

**Comment by ChristofferFlensburg** [comment]
Seems like I had the sense to isolate the code at least. Seems to be contained in the `findShiftManually` function in R/CNVnormalisation.R, with a switch in callCNV.R that checks for the secret flag and redirects.

The `clusters` input is the by-sample data frames you find in the saved superFreq clusters.Rdata. So would be like `clusters$clusters$mySample` or something like that as input to the function.

**Comment by andrewrech** [comment]
Hi Chris,

Thanks for your note. I will play around with this and determine if I can issue a PR, then close this either way.

Andrew

**Comment by ChristofferFlensburg** [comment]
Closing old issues.
