### ISSUE TITLE
error in RNA mode

### ISSUE THREAD

**Issue by km-2021** [ChristofferFlensburg/superFreq#105]
Hi,

RNA mode run stopped with error messages as follows;

Variants: 191419 
Unflagged : 191419 
Unflagged over 0%  freq : 0 
Unflagged over 20% freq : 0 
Median coverage over unflagged variants: 0 
Repeat flags: 0 
Mapping quality flags: 0 
Base quality flags: 0 
Strand bias flags: 0 
Single variant read flags: 0 
Minor variant flags: 0 
Stutter flags: 0 

Found no reads over any positions in the VCF. This is typically a sign of failing to read from the bam (/home/km/superFreq/GOTIC015.bam), bam index or fasta (/home/km/superFreq/resources/genomes). Or it can be an issue with samtools not being properly available. Cant recover, stopping here.
 FUN(X[[i]], ...): 
  Found no reads over any positions in the VCF. This is typically a sign of failing to read from the bam (/home/km/superFreq/GOTIC015.bam), bam index or fasta (/home/km/superFreq/resources/genomes). Or it can be an issue with samtools not being properly available.

Would you mind showing me how to solve it?

**Comment by ChristofferFlensburg** [comment]
The error message has the answer.

This is typically a sign of failing to read from the bam (/home/km/superFreq/GOTIC015.bam), bam index or fasta (/home/km/superFreq/resources/genomes).

In particular you see that the fasta file isn't a fasta file, it seems like it's the directory that contains the fasta files.
