### ISSUE TITLE
 Is it possible to track which subclones contain a specific genetic mutation in a superFreq riverplot?

### ISSUE THREAD

**Issue by km-2021** [ChristofferFlensburg/superFreq#111]
Is it possible to track which subclones contain a specific genetic mutation in a superFreq riverplot?

I am currently using superFreq to analyze a dataset of cancer genomes. I am interested in tracking the evolution of a specific genetic mutation over time. I would like to be able to see which subclones contain the mutation at each time point.

Is there a way to do this in superFreq?

**Comment by ChristofferFlensburg** [comment]
The most important mutations are shown in the plot, and there is an .xls next to the river plot with data on all assigned mutations. Note that not all mutations are assigned to a clone though.
