### ISSUE TITLE
Ok, I had a closer look at the latest Rsubread version, and they have indeed changed syntax for how to tell it to to count raw reads (not fragments) in PE samples. And that is most likely they cause of the bug. I made a change to superFreq that reads out the Rsubread version and does the appropriate call. Running tests and will push online, but will (hopefully) be next week. You can either backdate Rsubread if you're in a hurry, or wait for me to finish the testing and push changes online.

### ISSUE THREAD

**Issue by duanshumeng** [ChristofferFlensburg/superFreq#117]
Ok, I had a closer look at the latest Rsubread version, and they have indeed changed syntax for how to tell it to to count raw reads (not fragments) in PE samples. And that is most likely they cause of the bug. I made a change to superFreq that reads out the Rsubread version and does the appropriate call. Running tests and will push online, but will (hopefully) be next week. You can either backdate Rsubread if you're in a hurry, or wait for me to finish the testing and push changes online.

_Originally posted by @ChristofferFlensburg in https://github.com/ChristofferFlensburg/superFreq/issues/74#issuecomment-786409614_

**Comment by duanshumeng** [comment]
I also meet the trouble. The superFreq version 1.4.2 and Rsubread 2.8.2. 

ERROR: Paired-end reads were detected in single-end read library : /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/dsm_23110700129/HCC1395_DNA/HCC1395_WGS_bam/BGI_T20_WGS_2023_1_N.sorted.deduped.recaled.bam
No counts were generated.
Error in .stop_quietly() :
In addition: Warning message:
In read.table(sampleMetaDataFile, header = T, as.is = T, fill = T,  :
  incomplete final line found by readTableHeader on '/cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/dsm_23110700129/HCC1395_DNA/HCC1395_clonality/matadata_hcc1395-WGS.txt'
Error in featureCounts.
Input was
bamFiles: /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/dsm_23110700129/HCC1395_DNA/HCC1395_WGS_bam/BGI_T20_WGS_2023_1_N.sorted.deduped.recaled.bam /cpfs01/projects-HDD/cfff-e44ef5cf7aa5_HDD/dsm_23110700129/HCC1395_DNA/HCC1395_WGS_bam/BGI_T20_WGS_2023_1_T.sorted.deduped.recaled.bam
captureAnnotation[1:10,]: ? WASH7P WASH7P FAM138A ? ? OR4F5 ? ? ENST00000466430     1 10000 20000 30000 40000 50000 60000 70000 80000 90000  10000  20000  30000  40000  50000  60000  70000  80000  90000 100000 * * * * * * * * * * 1 1 1 1 1 1 1 1 1 1
Error in runDE(bamFiles, sampleNames, externalNormalCoverageBams, captureRegions,  :
  Error in featureCounts.
Calls: superFreq -> superFreq -> analyse -> runDE
Execution halted

I don't know how to deal this issue, please give me some advice. Thank you a lot!

**Comment by ChristofferFlensburg** [comment]
Hi! I believe that was fixed and should work in current superfreq version 1.5.1. Try updating superFreq and rerunning, and post a new issue if the problem persists in the current version.
