### ISSUE TITLE
Clonality of normal sample

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#12]
Hi Christoffer,

I am getting 0.5 clonality for a normal sample. Any idea why?

Thank you very much,

Gil
![clonal_normal](https://user-images.githubusercontent.com/25452585/28120931-37889308-6722-11e7-8392-79d05283fecf.PNG)

**Comment by ChristofferFlensburg** [comment]
That is a seriously messed up ploidy estimate. Definitely not desired behaviour. I hope that result came from the run with the bugged manual ploidy estimates? If it persists with automated ploidy, can you post the CNVcall plot?

**Comment by gilhornung** [comment]
Yes, apparently it came from the manual ploidy estimates...
Using the run with the slightly higher systematicVariance it is fine. Closing the issue.
Thanks!
