### ISSUE TITLE
Concermong about Normal reference

### ISSUE THREAD

**Issue by km-2021** [ChristofferFlensburg/superFreq#121]
To what extent does the gender bias in a normal reference with 10 cases affect the study's results?

**Comment by ChristofferFlensburg** [comment]
If you have only females, then you lose the ability to find recurring noise on chrY, but people typically don't care about chrY mutations, so probably not an issue. Perhaps more importantly, it affects copy number calling on sex chromosomes, but SuperFreq usually handles that well in most cases.

Sex is automatically determined (by comparing read depth between chrX and chrY, the score and result is shown in the log file), and "normal diploid" is then based on females and 2x read depth in males for chrX, and 2x read depth in males (ignoring females) for chrY. That allows us to use all data from all reference samples while still calling copy numbers with respect to 2 copies of DNA on sex chromsomes.
