### ISSUE TITLE
Can reference normal files include the same bam file used for input?

### ISSUE THREAD

**Issue by mlegarreta00** [ChristofferFlensburg/superFreq#122]
Hello,
I am new to the SuperFreq algorithm and trying to understand how it works. I'm trying to analyse a RNASeq normal-tumor sample and for that I have used the normal sample as one of the files included in the referenceNormals directory (along with a couple others obtained from the same patient). Is that okay or do I need to use reference normals that are different from the input files that I'm using?
Thank you in advance.

**Comment by ChristofferFlensburg** [comment]
Ideally the reference normals are different from the matched normal, and ideally with a different germline.
It'll still run, but there might be some artifacts in parts of the analysis.

For RNA-Seq, the most important part is that the reference normals are of a similar tissue as the analysed samples, so you might get better results from finding tissue-matching RNA-Seq samples from different data sets, even public data sets. Most public human sequencing data is access restricted, but there are also some open RNA-Seq data sets around, such as the leucegene project. Might be worth a look.
