### ISSUE TITLE
No reads in samples

### ISSUE THREAD

**Issue by mlegarreta00** [ChristofferFlensburg/superFreq#127]
While trying to run superfreq on a set of 8 samples the program stops after an hour or so running saying that there are no reads counted in any of the samples I have. I have checked the files and they are not empty and when I do samtools view -c <bam_file> I get a normal number of reads for every single file. Does anybody know how to fix this problem?
Thank you in advance.

**Comment by ChristofferFlensburg** [comment]
I'd start by double checking the settings, meta data and file permissions. Check that the genome is the correct one (mm10 vs hg38 for example), and that the bam files are at the path listed in the metadata, and available for reading from where you run superFreq.

If all that looks good, then look closer at the log file, in your R directory, which may have clues to what went wrong.
