### ISSUE TITLE
Mutations with non-zero clonality in the "normal" sample

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#13]
Hi Christoffer,

I noticed I have quite a few cases where I observe non-zero clonality in the normal sample (WS9-N in my case.) When I looked in IGV, I saw that indeed I have a couple of reads in the normal sample. Shouldn't these mutations be filtered out?

![river](https://user-images.githubusercontent.com/25452585/28147924-5a3779fe-678c-11e7-96ce-f950399a2758.PNG)
![igv](https://user-images.githubusercontent.com/25452585/28147930-63ae7d20-678c-11e7-88ea-9b94bc7acb0d.png)

**Comment by ChristofferFlensburg** [comment]
The art of somatic variant calling. :)

You can't really require 0 reads in the normal to call a somatic, or you'd lose a lot of SNVs that have a base miscall or whatever in the normal sample. Not to mention when you are detecting indels in repeat regions and more error-prone variants. Further, it is common that the matched normal sample has a low fraction of cancer cells in it. But on the other hand, the more variant reads you allow in the matched normal, the more false you'll include. Where to draw the line? Matter of taste. And this is part of the reason why different callers will give you very different sets of somatic mutations.

The IGV screenshot looks like a somatic SNV to me I have to say. Yeah, there are a couple variant reads in the normal, but it's a completely different VAF in the cancers. It definitely doesn't look like a germline variant, and it doesn't really look like noise either. So I'd say that it's a desired somatic SNV call. :P

**Comment by gilhornung** [comment]
Thank you.

Gil
