### ISSUE TITLE
NNNN as ref allele

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#15]
Hi Christoffer,

Another bug:

chr | start | end | reference | variant | inGene | severity | effect
-- | -- | -- | -- | -- | -- | -- | --
1 | 40150191 | 40150196 | NNNNNN | - | HPCAL4 | 10 | inframe_deletion

Same data as in the previous github issue.

All the best,

Gil

**Comment by ChristofferFlensburg** [comment]
hey!

The reported reference NNNN in deletions is a known issue that I probably won't fix soon. Essentially I set things up in a stupid way only accounting for SNVs, and including indels wasn't a big deal, apart from this reference information missing... That entire thing would need rewriting, but I think it's low reward per effort. So you'll have to deal with the NNN reference entries for now, sorry. I guess most people don't really care what bases are lost (maybe the VEP annotation will tell you which amino acids are lost in a later column?), and if you really care you can check in IGV.
