### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "db", value = c(TRUE, TRUE, TRUE, TRUE,  : replacement has 62328 rows, data has 60205

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#18]
Hi Christoffer,

I was able to complete a run for two individuals (I get some warnings, see below), but the third individual keeps failing. Here is error message:
```
Adding uncalled variants..Found 5853..Found 7172..Found 8839..Found 6423..done!
saving variants to  /gpfs/units/bioinformatics/projects/Sheba/MayaDadiani/INCPMPM-1568/analysis/batch1/run2/R/WS10/variants.WS10.Rdata ...done.
Importing dbSNP allele frequencies from superFreqDbSNP/dbAFnew.Rdata...done. Match against variants...Error in `$<-.data.frame`(`*tmp*`, "db", value = c(TRUE, TRUE, TRUE, TRUE,  :
  replacement has 62328 rows, data has 60205
In addition: Warning messages:
1: In checkSystem(vepCall) :
  'samtools --version' failed. This is likely to cause problems downstream in variant calling.
2: In mclapply(1:Nbatch, function(batchI) { :
  2 function calls resulted in an error
3: In mclapply(1:Nbatch, function(batchI) { :
  5 function calls resulted in an error
4: In mclapply(1:Nbatch, function(batchI) { :
  1 function calls resulted in an error
```

The R data dir can be found in the link below (you already know the password):
https://owncloud.incpm.weizmann.ac.il/index.php/s/Jg6wfEDYmV4YCI7

I am also getting warnings in the individuals that did work, I don't know if it is a related issue, or not.

```
2: In ebayes(fit = fit, proportion = proportion, stdev.coef.lim = stdev.coef.lim,  :
  Estimation of var.prior failed - set to default value
3: In ebayes(fit = fit, proportion = proportion, stdev.coef.lim = stdev.coef.lim,  :
  Estimation of var.prior failed - set to default value
4: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
5: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
6: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
7: In system(call, intern = T) :
  line 8 may be truncated in call to system(, intern = TRUE)
```

**Comment by ChristofferFlensburg** [comment]
Hey Gil,

Seems like a few of the parallelised batches of variant calling failed for the last three out of the four samples. There are checks in there that should throw some warning messages, but as I don't see the warnings I guess it must have crashed pretty hard. I'm tempted to guess memory issues? Is that possible? It seems pretty fast (each sample goes through the 50k positions in less than 2 minutes), so maybe you can dial down cpus a bit and try again?

I'm adding another check after the parallelisation that should catch this and throw a more meaningful warning. Maybe I should add a memory check as well...

**Comment by gilhornung** [comment]
Hi
We have a machine which should be fairly powerful. In the runs that crashed I used 24 CPUs.
I used forceRedo:

```
forceRedo$forceRedoNormalSNPs = TRUE
forceRedo$forceRedoSNPs = TRUE
forceRedo$forceRedoVariants = TRUE
forceRedo$forceRedoNormalVariants = TRUE
```

And run using 12 CPUS.
It crashed with the same error...

I am now running with 8 CPUs, after I deleted everything (instead of forceRedo)

**Comment by gilhornung** [comment]
Hi Christoffer!

I think I have found the source of the error.
The sample WS10-T has very high depth (the same sample was sequenced several times). When you run samtools mpileup, then in some cases you get very long lines (for example 8958 characters). The problem is that when it passes to R via system(...) then these long lines are broken into two cells, so if you had 1000 items, then you get 1001 items. I guess this causes a whole lot of mess downstream, and the "ret" data frame is not evaluated.

I am not sure on how to solve this, though.

Gil

**Comment by ChristofferFlensburg** [comment]
oohhh....
Well done on finding that! Thanks!
There are a number of ways around it.

I think there is an option about max read depth in samtools, which would rule out long lines. You lose data then of course. And it seems like the -d (--max-depth) option cant be set below 8000 for some reason. Weird. http://www.htslib.org/doc/samtools.html Worst case can always pipe into awk or something I guess, although it may slow it down somewhat. Should be fast compared to mpileup though... 

Otherwise write to temp file and then read in, but will be (more than) twice the I/O to disc so can potentially slow things down a lot, especially at high cpu where I/O is more often bottleneck. system() is a bit old as well... There is a newer system2() or something that supposedly is better. Maybe I'll look into that, would be best solution.

**Comment by gilhornung** [comment]
Hi,

I looked into the -d option. It doesn't do exactly what you would expect it to.
https://github.com/samtools/samtools/issues/29

I wasn't able to make system2() work. Do not know why.

I think that at least for my specific problem I will split WS10-T into three (It was actually the same sample sequenced 3 times)

Thanks,

Gil

**Comment by ChristofferFlensburg** [comment]
system2() has the same line-splitting behaviour. Hmm.

```
Value:

     If ‘stdout = TRUE’ or ‘stderr = TRUE’, a character vector giving
     the output of the command, one line per character string.  (Output
     lines of more than 8095 bytes will be split.)  If the command
     could not be run an R error is generated.  If ‘command’ runs but
     gives a non-zero exit status this will be reported with a warning
     and in the attribute ‘"status"’ of the result: an attribute
     ‘"errmsg"’ may also be available.
```

Best solution may be to just look for it in the system() output and re-join the lines in R. Should be fast compared to the rest of the parsing. Hopefully. I may not have time this week, but hopefully I should find time next week.

**Comment by ChristofferFlensburg** [comment]
Ok, the new patch 0.9.23 checks for truncated lines from samtools, and ignores those variants with a warning. Not perfect, but should at least not crash...

If you haven't got it running already, try on the new version. I'll close this for now, but feel free to reopen or make a new issue if it doesnt solve the problem.

Good luck, and thanks for finding the problem!

**Comment by gilhornung** [comment]
Thanks Chrisoffer!

I was also working on a solution.
I am piping the samtools pileup into Rscript and then saving the results as an Rdata file. After that I load the file and continue. I think this will have less I/O then saving the pileup as text. Here is the code snipplee:
```
   mpileup_rdata = paste0(bam, '_', index, '_', chr, '.pileup.RData')
   samtoolsCall = paste0(samtools_exe, ' mpileup -OsB -f ', fasta, ' -r ', region, ' -l ', posFile, ' ', bam,
	                  " | Rscript -e 'mpileups = readLines(file(\"stdin\")); save(mpileups, file=\"", mpileup_rdata, "\")'")
   system(samtoolsCall, intern=F, ignore.stderr=T)
   load(mpileup_rdata)
   return(mpileups)
```

The pipeline finished, so technically I should be fine, but looking the the results I see that the CNV in the "Normal" sample seem very weird (see image below). I don't know if it is due to my fix... I will download and run your patch, and see if everything is OK.
![ws10-n](https://user-images.githubusercontent.com/25452585/32335937-a644e2ce-bff6-11e7-9c80-a3e1be551fce.PNG)

**Comment by ChristofferFlensburg** [comment]
That's a lot of copy number segments...

The coverage going into the x-axis in this plot is calculated from the .bam through featureCounts (that should handle any read depth), so unless you change the .bam files itself, you can't blame the fix.

Either way, it's not only the coverage wrt the reference normals being noisy here, also the SNP VAFs (on the y-axis) seem pretty bimodal. Maybe have a look at the scatter between the normal and a cancer? You want something like the scatter in the second image in the README on this github page, but judging from the plot you posted here I don't think it'll look that clean.

**Comment by mubadav** [comment]
Hi Christoffer
So I started running superFreq, I keep on getting the error below, I have tried it on two patients so far. Apart from the solution given above, any idea as what may causing it, 

Error in `$<-.data.frame`(`*tmp*`, db, value = c(FALSE, TRUE, FALSE, FALSE,  : 
  replacement has 1602644 rows, data has 1316462
Calls: superFreq ... matchTodbSNPs -> lapply -> lapply -> FUN -> $<- -> $<-.data.frame
In addition: Warning messages:
1: In FUN(X[[i]], ...) : NAs introduced by coercion
2: In FUN(X[[i]], ...) : NAs introduced by coercion
3: In FUN(X[[i]], ...) : NAs introduced by coercion

**Comment by ChristofferFlensburg** [comment]
Hey Gil!

Hmm, yeah that really isn't an informative error message. I have a fair few bug fixes and quality of life changes locally that I have not pushed to github. I see 0.9.24 is like 6 months old... I'll run 0.9.25 through the tests and push it online probably tomorrow, then maybe I can have you rerun on that version? Just to avoid tracking down bugs that I already have fixed. If your error persists after that, I'll look at it closer.

cheers,
/Christoffer

**Comment by gilhornung** [comment]
Hi Christopher,
This time it is not me with the error....
Gil

**Comment by gilhornung** [comment]
I meant that I didn't report the error :-)

**Comment by ChristofferFlensburg** [comment]
Omg, now I get it... Reading comprehension fail on my end! Sorry Gil and David! :D 

David: I'm running some tests and I'll give you an updated version that may or may not fix your issues.

**Comment by ChristofferFlensburg** [comment]
Ok David, I ran my local version through the tests and it all passed. Just pushed online. Try updating and run again. If it persists, maybe you can send me the .log file, which is in Rdirectory.

**Comment by ChristofferFlensburg** [comment]
This ticket is old, so I'm assuming it was either fixed or no longer relevant. I'll close, but feel free to reopen create a new issue if still relevant.
