### ISSUE TITLE
Does superFreq work with VCFs containing indels, such as from MuTect2?

### ISSUE THREAD

**Issue by andrewrech** [ChristofferFlensburg/superFreq#19]
Hello Christoffer,

Thank you for developing this wonderful tool.

Does superFreq work with VCFs containing indels, such as from MuTect2?

**Comment by ChristofferFlensburg** [comment]
Hi Andrew,

Thanks! :)

Yes. it works fine for short indels of a few basepairs, but when you start reaching 10+ bp I think sensitivity may drop off a fair bit. I haven't done proper testing on this though, just my experience. So superFreq does handle them, but is not a dedicated indel caller.

**Comment by andrewrech** [comment]
Great - thanks!
