### ISSUE TITLE
Documentation does not build

### ISSUE THREAD

**Issue by andrewrech** [ChristofferFlensburg/superFreq#20]
Christoffer ツ,

Looks like a character is causing your docs to error:

```r
system(paste(shQuote(file.path(R.home("bin"), "R")),
    "CMD", "Rd2pdf", shQuote(find.package("superFreq"))))
```

```
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  :
  Running 'texi2dvi' on 'Rd2.tex' failed.
LaTeX errors:
/<path>/.Rd2pdf84338/Rd2.tex:1611: Package inputenc Error: Un
icode char ツ (U+30C4)
(inputenc)                not set up for use with LaTeX.
```

```r
sessionInfo()
```

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: macOS High Sierra 10.13

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.1 parallel_3.4.1
```

**Comment by ChristofferFlensburg** [comment]
Ah well, who needs documentation. ¯\_(ツ)_/¯

**Comment by ChristofferFlensburg** [comment]
Ok, let me be serious. :)

What are you trying to do? Build a .pdf from something?

**Comment by andrewrech** [comment]
Trying to build a pdf of your package documentation, (as occurs when you build the package yourself or upload to CRAN), but it seems that character is causing my Latex to freq out.

**Comment by andrewrech** [comment]
For instance:

```r
system(paste(shQuote(file.path(R.home("bin"), "R")),
    "CMD", "Rd2pdf", shQuote(find.package("ggplot2"))))
```

**Comment by ChristofferFlensburg** [comment]
Hmm, ok. Seems like you may be the first to do that, thanks!

Is there a way to make this work with the character you think? Otherwise I'll just remove it from the docs I guess. :(

**Comment by andrewrech** [comment]
[Perhaps](https://tex.stackexchange.com/a/86913): `\usepackage[utf8x]{inputenc}`

**Comment by ChristofferFlensburg** [comment]
Hmm, I'll look into it quickly, otherwise I'll just remove. It's just a little easter egg anyway. Do you need it patched asap, or can it wait for next patch (maybe at the end of the week with some luck)?

**Comment by andrewrech** [comment]
Nah happy to look through on GH, no urgency at all

thanks!

**Comment by ChristofferFlensburg** [comment]
Ok, so I'll leave it as it is for now. If you don't find a solution and it still causes you troubles, post here again and I'll remove the odd characters. Sorry about that, cheers.

**Comment by ChristofferFlensburg** [comment]
I'm cleaning up open issues, and I'll close this as it seems unlikely to cause (significant) problems at this stage? I'm still not 100% sure when this issue appears though, as I find this concept of "reading about things before using them" confusing. So again, if it does, feel free to reopen or create a new issue.
