### ISSUE TITLE
Does superFreq have any 'cohort dependencies'

### ISSUE THREAD

**Issue by andrewrech** [ChristofferFlensburg/superFreq#21]
Hello Christoffer,

Provided I supply normals appropriately, can I split tumor samples across cluster nodes / R processes? Do any steps of superFreq require the full cohort of samples (n > 100 in my case) to be processed together?

Thanks

**Comment by ChristofferFlensburg** [comment]
Hey!

SuperFreq analyses samples from the same individual (as marked in the meta data file) together, but not across individuals. I guess all of your samples are not from the same individual, as you use the word cohort. :)

The best way to split individuals across runs on a server is to use the participant= option of the superFreq call, which limits the run to only the given individual(s) and allows you to parallelise. I don't recommend parallelising superFreq() calls within R though, as I usually experience issues with the plotting when I do. Better to pass the participant= argument as input to the Rscript call of your .R file. All this requires splitRun=T, but I assume you already have that. I suggest running only one individual first, as a test, but also to allow the first run to set up resources that only need to be done once (like annotate capture regions, do counts for the reference normals, etc). Later runs will then reuse that information.

``` sh
Rscript runSuperFreq.R case1
Rscript runSuperFreq.R case2
...
```

There is an afterburner for cohorts as well, that isn't really document well, but it's decently mature by now. I should probably document it a bit better and advertise it. Maybe a paper... It summarises copy numbers over different regions of the genome, and identifies genes that are frequently mutated. Have a look at:

``` R
?mergeBatches
?cohortAnalyseBatch
```

Or you can look at one of the test runs I make, which is a "usual" superFreq setup and run, followed by cohort analysis of all the involved individuals. You should be able to reuse the last part more or less by just copy-pasting it. You only need to run it once though, so if you are making 100 calls to the runSuperFreq.R for each case, you don't want to have that called every time. Run this only after all the individuals are done.

``` R
#Loads the superFreq library.
library(superFreq)


#path to the metadata file: a tab separated file with the named columns as in the example file.
#path to bamfiles are relative from the directory of the metadata file.
metaDataFile = 'metaData.txt'


# The capture regions: A bed file.
# So a tab separated chr start end. Use unpadded regions, superFreq pads these.
# If capture regions are not available, it seems to work well to use all exons of genes for an exome.
captureRegionsFile = 'captureRegions/captureRegions.bed'

#directory with the pool of normals. These normal samples don't have to (but can) be from the same individuals,
#but have to have the same capture regions. The more normals, the better, minimum of 2 to estimate variance.
#More reference normals increase run time though. 5-10 is often a good compromise.
#These samples should not have a cancer content of more than about 1%, or it may cause false negatives.
#The directory has to have a subdirectory names 'bam' with (links to) the reference normal bam and index files.
normalDirectory = 'normals'

#path to where the saved R data and log file will be stored.
#The containing directory must exist.
Rdirectory = 'R'

#path to where the plots and other output to go.
#this is where you will look at your output.
#The containing directory must exist.
plotDirectory = 'plots'

#maximum number of cpus to be used. This also affect memory usage.
cpus=5

#The base quality phred offset. This can be read from fastqc analysis for example.
#Most technologies have 33 these days.
BQoffset = 33

#the reference genome name. Only hg19, hg38 and mm10 supported in version 0.9.16.
genome = 'hg19'

#the fasta file the BAMs are aligned to.
reference = 'reference/hg19.fa'

#If you want to redo some part of the analyses (rather than access the previously saved data
#from earlier runs) you need to change this setting. For example forceRedoEverything().
forceRedo = forceRedoNothing()

#The two parameters of the CNV calling analysis. Essentially setting how much trust to put in
#the read depth and the SNP frequencies.
#SystematicVariance = 0 is the most sensitive to read depth signal, but also more prone to false positives.
#maxCov = Inf is the most sensitive to SNP frequency signals, but also more prone to false positives.
#systematicVariance = 0.02 and maxCov = 150 is default for exomes.
systematicVariance=0.02
maxCov=150

#for data sets with multiple participants, turning this option on makes superFreq run one participant at a time.
#It saves resources and CPU time, so recommended if multiple participants.
splitRun = T

vepCall = 'vep --dir_cache /stornext/HPCScratch/cache/.vep --offline'

#Run the analysis.
data =
  superFreq(metaDataFile, captureRegions=captureRegionsFile, normalDirectory=normalDirectory,
            Rdirectory=Rdirectory, plotDirectory=plotDirectory, reference=reference, genome=genome,
            BQoffset=BQoffset, cpus=cpus, forceRedo=forceRedo, systematicVariance=systematicVariance,
            maxCov=maxCov, splitRun=splitRun, manualStoryMerge=F, vepCall=vepCall)


#if you want a cohort analysis of recurring mutations over all participants, switch this on.
runCohortAnalysis = F
if ( runCohortAnalysis ) {
  
  metaDataFiles = list.files('splitMetaData', pattern='*.tsv', full.names=T)
  participants = gsub('\\.tsv$', '', basename(metaDataFiles))
  Rdirectories = paste0('/R/', sample)
  
  paths = data.frame('metaDataFile' = metaDataFiles, 'Rdirectory'= Rdirectories)

  if ( !dir.exists('cohort') ) dir.create('cohort')
  targetMetaDataFile = 'cohort/metaData.tsv'
  targetRdirectory = 'cohort/R'

  mergedPaths = mergeBatches(paths, targetMetaDataFile, targetRdirectory)
     
  outputDirectories = list('Rdirectory'=targetRdirectory)
  cohortAnalyseBatch(targetMetaDataFile, outputDirectories, cpus=8, genome=genome, cosmicDirectory='/wehisan/general/academic/grp_leukemia_genomics/data/resources/COSMIC/')
}
```

**Comment by andrewrech** [comment]
Thanks for this detailed answer and pointer to code.

> I guess all of your samples are not from the same individual, as you use the word cohort.

I'm sorry I wrote my question confusingly - many samples are from the same individual, and I would run one individual per node as required.

>  Maybe a paper... It summarises copy numbers over different regions of the genome, and identifies genes that are frequently mutated. 

Looking forward to trying this.
