### ISSUE TITLE
Many variants disappear between variantsBI and allVariants

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#28]
Hi Christoffer,

I noticed a large drop in the number of variants that are stored in variantBI and in allVariants. In the sample below about 10,000 variants are gone. Moreover, there are good somatic variants among the variants that are gone (I don't know to what extent). An IGV inage of one very clear somatic variant is also shown below.

A link to the run log:
https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/a13KOqkyE1Wl9K0

```
> variants$WS10.R %>%
+      anti_join(allVariants$variants$variants$WS10.R, by="x") %>%
+      nrow()
[1] 10497
```

![ws10r_1_243456735](https://user-images.githubusercontent.com/25452585/33742286-4e3a15a6-dbb0-11e7-8aca-9070236a4fdf.PNG)

**Comment by ChristofferFlensburg** [comment]
I think this must be the filter that removes variants that are at very low VAF in all samples. I see the variant you show is at 0% and 2% which I think is below the threshold.

I wouldn't call that a very clear somatic variant. The p-value from a fisher exact test is 9% without multiple hypothesis correction, so you'd risk a lot of false calls if you start calling this kind of variants.

**Comment by gilhornung** [comment]
OK, thank you. It was unclear to me.
Maybe it would be clearer if you kept the variant through the stages, but had it flagged by "low VAF" flag or something like that. Just to maintain consistency...
