### ISSUE TITLE
any error message related to VEP

### ISSUE THREAD

**Issue by ChristofferFlensburg** [ChristofferFlensburg/superFreq#3]
SuperFreq makes a system call to VEP to annotate variants. While I have tried to cover the typical way that people set up VEP, it can easily go wrong.

Check in the log file (in the `Rdirectory`, runtimeTracking.log) how superFreq tries to call VEP. Try to run the command manually on the command line, see if you can reproduce the error. Try to find the desired VEP command, and then adjust the `vepCall` option in the superFreq() function.

Ideally I'd switch to a variant annotator working entirely in R to avoid this annoying dependence on a VEP system call. Taking suggestions for good R-based variant effect callers. :)

**Comment by ChristofferFlensburg** [comment]
Typically you want to use a local downloaded annotation (or it can be very slow). For that, add in the --offline and the path to the cache if not in the default location. So if VEP doesn't run, something like

``` R
vepCall = 'vep --dir_cache /path/to/my/VEP/cache/.vep --offline'

superFreq(..., vepCall=vepCall)
```

Is a good first try to fix it.

**Comment by sraorao** [comment]
When VEP finishes with an error for one of the samples (e.g., leaving an incomplete VEP.txt), superFreq continues VEPing the next sample. Might it be better to make superFreq stop there rather than continue on? (especially because superfreq runs vep with `--force-overwrite` by default, so even the successful samples will get overwritten)

I suppose this is partly an issue because VEP is an external dependency as you said above. I'm guessing you have tried VariantAnnotation R package, although I haven't used it much so don't know how it compares to VEP output.

**Comment by ChristofferFlensburg** [comment]
Hmm, yes. Warning vs error. I agree that if things are screwed up, there is no reason to continue. Better to stop and try to give an informative error. Thing with VEP is that superFreq isn't very reliable in detecting whether VEP actually did finish or not. It just checked for a "Finished" in the output, but I'm not sure all VEP version always output that... I know that I people sometimes get the VEP warning even with a successful run. So to do throw an error instead, I'd need a better way to detect VEP success first. :/

I did come across VariantAnnotation at some stage. Looking at it again now, I'm not sure why I didn't want to use it. Seems like it's ticking all the boxes. Essentially all I use from VEP is the protein change, severity, and PolyPhen/SIFT status. Seems like VariantAnnotation does that. I should have a go at some point. Or anyone with spare time. :o) it's the runVEP() function that should be replaced. runVariantAnnotation() maybe?

**Comment by ChristofferFlensburg** [comment]
So you got the warning, but variants still annotated? VEP typically gives many output lines for each input line (one for each transcript the variant is close to). I could check that it's not 0 though, or that most variants finds annotation... Or better get the exit status of the command, but not sure how to do that from R.

Yeah, I recently learned that R parallelisation doesn't play well with the R garbage collection. Essentially it SHOULD be copy-on-write for forks, but whenever the garbage collector runs, it counts as write for all objects. So important to do the superFreq run from a clean R session, as everything you have floating around risks getting copied `cpus` times. If you still have memory issues, try lowering the 'cpus' parameter otherwise. SuperFreq doesn't parallelise everything so you quickly run into diminished returns when you increase cpus.

**Comment by sraorao** [comment]
> So you got the warning, but variants still annotated?

The first time, VEP quit one sample with an error and continued on with the next sample, which I noticed soon after and terminated superFreq. When I restarted the run, VEP ran fine, but superFreq ended with 5 warnings (I had 5 samples in the run) saying VEP may not have finished properly.

> VEP typically gives many output lines for each input line (one for each transcript the variant is close to).

I was thinking more like testing `nrows(samples.txt) == length(unique(sample.VEP.txt$locus))`, where `locus` is `paste0(chr, pos)`. An equivalent test at the command line (awk | sort -u | wc -l) worked for me. In my experience, VEP returned _at least_ one line for each variant, but I have only worked with sequencing data from exons, so maybe that's a wrong assumption!

> If you still have memory issues, try lowering the 'cpus' parameter otherwise. SuperFreq doesn't parallelise everything so you quickly run into diminished returns when you increase cpus.

Got it.

**Comment by ChristofferFlensburg** [comment]
So just worked second time you ran? Huh... VEP doing weird things.

Yeah, that's probably more reliable than the current warning. I'm still not sure I'd trust it enough to throw an error though. May not return things for intergenic variants as you say. I had a quick look at how system() handles non-zero exit status, and seems like it should throw a warning...

```
     If ‘intern = TRUE’, a character vector giving the output of the
     command, one line per character string.  (Output lines of more
     than 8095 bytes will be split.)  If the command could not be run
     an R error is generated.  If ‘command’ runs but gives a non-zero
     exit status this will be reported with a warning and in the
     attribute ‘"status"’ of the result: an attribute ‘"errmsg"’ may
     also be available
```
Do you remember what the warnings said?

But at this point I"m tempted to leave it like this and look into VariantAnnotation instead...

**Comment by sraorao** [comment]
Sorry, don't remember what the warnings said exactly, and I can't find them in the log file! I will make note if I see that again.

**Comment by ChristofferFlensburg** [comment]
As of version 1.1, VEP is no longer required, so I can finally close this ticket! (thumb it up plz :D)
