### ISSUE TITLE
Error in download.file

### ISSUE THREAD

**Issue by ChristofferFlensburg** [ChristofferFlensburg/superFreq#32]
Seems like the WEHI gitlab is offline atm, which means that superFreq can't download the resources needed. If you already run superFreq, then you can reuse old resources (just set resourceDirectory to that of a previous run), but first-time users will get errors. Working on fixing this, but feel free to contact me to get the files through other means in the meanwhile if needed.

For the future, it might be a good idea to have a mirror somewhere for when this happens, and an option for which mirror to use.
Any suggestions? Would just some google documents work? :/

**Comment by kvaldez** [comment]
Is there an update on this?  It looks like the WEHI gitlab is offline now, and although I ran superFreq previously, I used a different reference genome so I'm unable to use the same resources.

Is there any word on when the gitlab will be back up?

**Comment by kvaldez** [comment]
Is this in any way connected?

[<img width="940" alt="Screen Shot 2019-07-31 at 3 09 56 PM" src="https://user-images.githubusercontent.com/19807160/62240631-5e9f8880-b3a5-11e9-9224-5e47e618157b.png">
](https://sysbio-mascot.wehi.edu.au/mascot/closing.html)

**Comment by ChristofferFlensburg** [comment]
Hi Kristin,

Yep, gitlab is offline for me as well. There were some major issues related to a blackout yesterday morning local time (about 24h from this post), that might've been the cause. Maybe gitlab didn't make it back online. I've alerted admins, and I am putting a mirror up now (I think figshare).

I'll report back on progress (I hope both gitlab and mirror should be online by end of day), thanks for the alert and sorry for the inconvenience.
/Christoffer

**Comment by ChristofferFlensburg** [comment]
Admins reacted quickly and confirmed it was related to yesterday's issues, and it should be back online now. Seems to work for me at least, have a try. I'll still try to get a figshare mirror up, and maybe even an informative error message pointing to the mirror in case the automated download fails.

**Comment by ChristofferFlensburg** [comment]
Mirror is online (for manual download) at https://figshare.com/articles/superFreqResources_tar_gz/9202289. I'm adding in an error message that will go online next version.

**Comment by kvaldez** [comment]
Hi Christoffer,

Thanks for the quick reply, and for adding the mirror site.  It is up and running here too!

Regards,
Kristin
