### ISSUE TITLE
R script dies on loading the reference genome

### ISSUE THREAD

**Issue by aleighbrown** [ChristofferFlensburg/superFreq#35]
Running on a cluster, so this may be a part of why it's dying, but running the script gets this stage

"Done and saved named file, now proceeding to binding strength.
Loading genome from /fdb/GATK_resource_bundle/hg19-2.8/ucsc.hg19.fasta"

and then it gets killed. 

Any ideas why this could be happening? Pretty sure I have enough memory for it. Does the script attempt to write anything to the same folder as the ref genome?

**Comment by aleighgreen** [comment]
Looks to be a problem in 

`ret = read.fasta("/fdb/indexes/hg19/hg19.fa", seqtype='DNA')`

as other methods to read in fasta files, including readDNAStringSet, and FaFile are working fine.

**Comment by ChristofferFlensburg** [comment]
Thanks for the bug report and the work to track down the cause! Much appreciated! :)

I haven't seen that before. It shouldn't be writing anything afaik, but who knows what is happening deep down in these functions. So no error message from R, the job just get killed like that? Any error message from the job handler? Have you tried running it interactively? How much memory did you give it? It'd just be easier with an error message of some kind.

I am using FaFile in another part of the software (in the annotation), so could swap to that, but I'd like to understand what is wrong with read.fasta(). I think the first call with FaFile doesn't actually read form the file, but only sets up a stream, so maybe it wouldn't trigger issues with reading from the file when you test it. Don't know about readDNAStringSet though.

**Comment by aleighgreen** [comment]
Yeah it just runs forever, without giving an error, I've tested on interactive as well. I've got 24g of mem so I doubt it's that. 

`ret = readDNAStringSet("/fdb/indexes/hg19/hg19.fa")`

Changing to this line runs fine, although may have caused me some downstream headaches, as the very least it got through the  `addBindingStrength` function which is where it was previously crashing. 


For what it's worth, from what I understand of how this function works, you might get a lot of speeding up  in this function `rangesToBindingScore` by using a combination of 
getSeq(captureregions, Bsgeneome)
nucleotideFrequencyAt()
dinucleotideFrequency()

All of these from the BSgenome package and Biostrings respectively. 

readDNAStringSet is also from Biostrings.

**Comment by ChristofferFlensburg** [comment]
How long is forever? It can take a while. I'd probably wait at least an hour before I give up.
As with the other issue, you will bypass this if you just don't specify the capture regions, as it'll download and use the preprocessed .bed.

Those are good suggestions, thanks!
I am considering dropping support for this entire part of the program though, so I might not put in too much work in it, sorry. :/

**Comment by aleighgreen** [comment]
Over an hour. I think the top I waited was about 3 hrs

**Comment by ChristofferFlensburg** [comment]
Closing old issues.

I believe this should be fixed anyway, feel free to make a new issue if still a problem.
