### ISSUE TITLE
Integrating validation data into superFreq

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#37]
Hi Christoffer!

Long time since I wrote... Hope all is well.
We finally have validation data (IonTorrent) for specific sites in our data, and we would like to integrate them back into the models that superFreq constructed.
Any suggestions on how to do it properly?

Thank you, and Happy New Year!

Gil

**Comment by ChristofferFlensburg** [comment]
Hey Gil!

All good, hope you are well and happy new year!

Let me understand: you did some analysis on exomes, involving calling point mutations, and you then generated targeted sequencing data over some of the called sites, and you now want to compare them to the original calls from the exomes?

It's a bit outside the scope of superFreq, but you could hack something together. You could run pairwise analysis of the original exome against the validation data, supplying a vcf of only the variants you want to validate. Then go and look at the scatter plots to compare the VAFs.

You could also run the clonal tracking on the validation data only and see what happens. SuperFreq isn't really made for that kind of validation data though. My experience on amplicaons is that it can be a bit trigger happy on filtering out variants that have very deep read depth.

If you want it integrated in the sense that you want the validation data to inform the clonal tracking together with all of the other calls... Hmm, don't think that can be done easily right now, sorry. There is no option in the meta data to mark two samples as replicates as you would need here. Could potentially be a nice additions, but don't think I'll find the time to implement that in a while. It's also not clear how it should be done in a sensible way, particularly when the validation data is from a different tech.

So hmm. Not sure I can help you much here, sorry.

**Comment by gilhornung** [comment]
Hi Christoffer,

Thanks for the reply. Indeed, I generated targeted sequencing (IonTorrent) data over some of the variants I called in a previous set. 

I thought there was something which was more built in to superFreq, because you mentioned in your CASCADE paper (PLoS medicine 2016) that:
"To validate this approach, high depth validation sequencing of mutations found in more than one sample was subjected to the same process to check the consistency of the tree with the WES data."

From this I gather that you re-run the clonal tracking on the validation data, but did not use the new data to improve the model, right?

Thank you,

Gil

**Comment by ChristofferFlensburg** [comment]
Hmm, it was Christophe actually doing most of the analysis for that paper, I was just supporting. I'll forward this issue to him and maybe he can weigh in. So I don't remember exactly what was done, but I think it was more a matter of validation through deep sequencing and then manually, or at least outside superFreq, checking that the VAFs match what we expected form the clonal tracking of the exomes.

So as far as I'm aware, the deep sequencing data was never run in superFreq. You could I guess, in theory at least, but not sure how superFreq performs for that kind of data.

Good luck!
/Christoffer

**Comment by gilhornung** [comment]
No need to leave this open...
