### ISSUE TITLE
clonality versus cancer cell fraction

### ISSUE THREAD

**Issue by kvaldez** [ChristofferFlensburg/superFreq#44]
Hi Christoffer,

On the excel spreadsheet that comes with the river plots... is clonality basically the same as cancer cell fraction (CCF)?

Thanks,
Kristin

**Comment by ChristofferFlensburg** [comment]
Hi Kristin!

Clonality in the superFreq output means the cellular fraction of the sample, not of the cancer.

It's a conscious choice to not try to normalise away the cancer purity of the samples, as the purity can be difficult to get right. Normalisating to CCF with an incorrect purity invalidates all the other clonalities, including more robust ones, so I don't find it a good trade in terms of risk/reward.
