### ISSUE TITLE
cbind(): number of rows and matrices must match

### ISSUE THREAD

**Issue by adbeggs** [ChristofferFlensburg/superFreq#45]
Hi Christoffer,

Great tool! I have already used it succesfully on another sample set but I am struggling to get it to run on a triplet sample set (i.e. tumour normal and another tumour at a later timepoint - CRS in this case). It runs then crashes out with the error below - can you help?

Thank you!

ANdrew 

 

> 2019-10-19 22:46:30 
>  Imported and sanity checked meta data. Looking good so far!
>  metadata:
>    BAM   VCF   NAME   INDIVIDUAL   NORMAL   TIMEPOINT   
>    /storage2/exome/C1_S1.bam   /storage2/exome/splitMetaData/NA   C1   Patient1   NO   CRS   
>    /storage2/exome/N1_S1.bam   /storage2/exome/splitMetaData/NA   N1   Patient1   YES   Normal   
>    /storage2/exome/P1_S1.bam   /storage2/exome/splitMetaData/NA   P1   Patient1   NO   Tumour   
> 
>  timeSeries:
>    C1   N1   P1   
> 
> ##################################################################################################
> 
> 2019-10-19 22:46:31 
> Current memory use (Mb): 551.9, max use (Mb): 551.9
> Starting differential coverage analysis by sample.
> Preparing capture regions for featureCounts..done.
> Counting reads over capture regions.
> 
>         ==========     _____ _    _ ____  _____  ______          _____  
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.34.7
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 3 BAM files                                      ||
> ||                           o C1_S1.bam                                      ||
> ||                           o N1_S1.bam                                      ||
> ||                           o P1_S1.bam                                      ||
> ||                                                                            ||
> ||              Annotation : R data.frame                                     ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 4                                                ||
> ||                   Level : feature level                                    ||
> ||              Paired-end : yes                                              ||
> ||      Multimapping reads : counted                                          ||
> || Multi-overlapping reads : counted                                          ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : counted                                          ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\============================================================================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file .Rsubread_UserProvidedAnnotation_pid13109 ...         ||
> ||    Features : 233285                                                       ||
> ||    Meta-features : 23567                                                   ||
> ||    Chromosomes/contigs : 24                                                ||
> ||                                                                            ||
> || Process BAM file C1_S1.bam...                                              ||
> ||    Paired-end reads are included.                                          ||
> ||    Total alignments : 69484349                                             ||
> ||    Successfully assigned alignments : 4938461 (7.1%)                       ||
> ||    Running time : 1.36 minutes                                             ||
> ||                                                                            ||
> || Process BAM file N1_S1.bam...                                              ||
> ||    Paired-end reads are included.                                          ||
> ||    Total alignments : 56492247                                             ||
> ||    Successfully assigned alignments : 4048763 (7.2%)                       ||
> ||    Running time : 1.10 minutes                                             ||
> ||                                                                            ||
> || Process BAM file P1_S1.bam...                                              ||
> ||    Paired-end reads are included.                                          ||
> ||    Total alignments : 23077189                                             ||
> ||    Successfully assigned alignments : 1688726 (7.3%)                       ||
> ||    Running time : 0.39 minutes                                             ||
> ||                                                                            ||
> ||                                                                            ||
> \\============================================================================//
> 
> Got a sample count matrix of size 233285 3 , with total counts:
> C1.S1.bam :  5022011 
> N1.S1.bam :  4114940 
> P1.S1.bam :  1718995 
> Saving sample counts to /storage2/sallyexome/R/Patient1/fCsExon.Rdata..done.
> Loading normals counts from file..done.
> Loaded normal counts of dimension 224667 2 
> Merging sample and normals counts..Error in cbind(...) : number of rows of matrices must match (see arg 2)
> In addition: There were 48 warnings (use warnings() to see them)
>

**Comment by adbeggs** [comment]
Okay - solved that problem - incompatible genomes. There is another problem however, now I get this:
```

Variants for Patient1 
Reading file /storage2/sallyexome/splitMetaData/./NA...done.
Processing data...Error in `.rowNamesDF<-`(x, value = value) : 
  missing values in 'row.names' are not allowed
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by ChristofferFlensburg** [comment]
Hi Andrew!

Yep, the first error happens when you have different capture regions (such as from different genome builds) pointing to the same reference normal directory, but I think there should be a decently informative error in that case?

The other problem seems to be related to the metaData (thanks for giving me the full log, allowing me to see that). The VCF column has all entries  /storage2/exome/splitMetaData/NA, which probably isn't what you want.

good luck, let me know if there are more issues!

cheers,
/Christoffer

**Comment by ChristofferFlensburg** [comment]
Oh, I think you realise, but just to make sure: you can't use a normalDirectory with hg19 bam files as reference normals for an hg38 run, or the other way around. `genome` and `mode` (and `captureRegions` if you specify that option) need to match between all runs pointing to the same reference normal directory.

**Comment by ChristofferFlensburg** [comment]
Closing old issues.
