### ISSUE TITLE
Incorrect determination of sex

### ISSUE THREAD

**Issue by kvaldez** [ChristofferFlensburg/superFreq#46]
Hi Christoffer,

I ran superFreq on my dataset of 3 patients, 4 tumor samples each, with matched normals.  I noticed an odd output on the copy number calling for one of the samples, in which the copy number was abnormally low across all chromosomes.  I also noticed in the superFreq output, that the patient's matched normal was determined to be male, but one of the samples was incorrectly determined to be female.  

Is there a way to predetermine the sex of the samples, or correct this in some way, so that I may obtain the proper copy number output?  Or is it possible that there's another cause?  The sample with the low copy number isn't the one that was determined to be female.

The matched normal for the J3 samples is P_S15.recal below:

> Determining sex..done.
> SAMPLE   SCORE   SEX   
> J3_T4   0.1737877   male   
> J3_T1_cells   0.07024928   male   
> J3_T4_cells   0.1649504   male   
> J3_T1   -0.05445427   female   
> J3_norm   0.4329829   male   
> P_S15.recal   0.4329829   male   
> Q_S14.recal   -0.3213564   female   
> R_S13.recal   0.4553316   male

 

![summary](https://user-images.githubusercontent.com/19807160/72081362-5a6c8500-32cc-11ea-8bd6-b8f1308a83ca.png)

**Comment by ChristofferFlensburg** [comment]
Hi kvaldez!

It seems superFreq called a lower ploidy for J3_T4 than for the other samples from that patient. This might be real (the other three underwent genome duplication, but J3_T4 didn't), or it might be an incorrect ploidy call. In general, calling ploidy from sequencing data alone is very difficult, so very possible that thew ploidy is wrong. I don't think the ploidy call is related to the called sex of the samples in this case.

I recently (so you may need to update and rerun if not on latest version) added some more infrastructure around ploidy of samples, and it should now be possible for you to encourage superFreq to pick certain ploidies. The algorithm is explained in section 1.6.2 of the supplementary methods: https://www.biorxiv.org/content/10.1101/380097v2.supplementary-material. If you go to the diagnostics directory of your plots, you'll find maypole plots (diagnostics/CNVcall) as well as the ploidy fitness curve (diangostics/ploidy). Probably you'll find two local minima for J3_T4, one lower and one similar to the other samples. Likely the other three samples also have two local minima, but favoured the higher one. If you want to force the higher ploidy for J3_T4, you can rerun `superFreq()` and set the `ploidyPrior` setting for J3_T4 to something close to the desired local minimum. This feature is still pretty new, and while I've tested it internally, I'm not sure how much it's been used "in the wild", so let me know how it goes! Even if it works as intended, I'd be happy to hear that it actually works outside of WEHI as well!

Regarding the incorrect sex call: The sex is called from just the relative read depth on chrX and chrY. While very simple, it usually is reliable and I really don't see it wrong often, so when wrong, it can be a sign of QC issues. So first thing I'd double check that samples aren't mislabeled or anything (easy to see from the scatters). It might also just be a case of loss of chrY, which happens sometimes in older males. If you want to dig into that further, I'd want to look at the CNV plots. The plot you attached is good for looking at all CNAs at the same time, but it doesn't separate 1 copy from 0 copies (both blue).

Good luck, let me know how it goes!

cheers,
/Christoffer

**Comment by kvaldez** [comment]
Hi Christoffer,

Thank you so much for your insight and quick response!  I updated my superFreq package and re-ran my data, and sure enough there were two ploidy calls for each samples. For J3_T4, the higher minima was closer to the chosen minima for the other samples.  

![J3_norm](https://user-images.githubusercontent.com/19807160/72379750-073a6e00-36e2-11ea-97ea-c529f2d99d55.png)
![J3_T1_cells](https://user-images.githubusercontent.com/19807160/72379751-073a6e00-36e2-11ea-9868-4616c08f0dbb.png)
![J3_T1](https://user-images.githubusercontent.com/19807160/72379752-073a6e00-36e2-11ea-86d5-329d3977c419.png)
![J3_T4_cells](https://user-images.githubusercontent.com/19807160/72379753-073a6e00-36e2-11ea-8cff-5b0c0db69ed1.png)
![J3_T4](https://user-images.githubusercontent.com/19807160/72379755-073a6e00-36e2-11ea-8d90-fe8277814e18.png)

One question though, how do I set the ploidyPrior argument?  I went through the superFreq() arguments but can't seem to figure this out.

I'm less concerned about the errant sex determination now that I know it's not related to the ploidy call, but I attached the CNV plots to get your take on this. They all seem to similar for X and Y to me, but there may be something I'm missing here!  

[J3_norm.pdf](https://github.com/ChristofferFlensburg/superFreq/files/4061329/J3_norm.pdf)
[J3_T1_cells.pdf](https://github.com/ChristofferFlensburg/superFreq/files/4061330/J3_T1_cells.pdf)
[J3_T1.pdf](https://github.com/ChristofferFlensburg/superFreq/files/4061331/J3_T1.pdf)
[J3_T4_cells.pdf](https://github.com/ChristofferFlensburg/superFreq/files/4061332/J3_T4_cells.pdf)
[J3_T4.pdf](https://github.com/ChristofferFlensburg/superFreq/files/4061333/J3_T4.pdf)


Great app, and thanks again for your help.

Best,
Kristin

**Comment by ChristofferFlensburg** [comment]
Wow that's really a textbook example of this threshold effect for picking either the higher or lower ploidy! All samples have two minima, but T4 has the lower ploidy minimum just slightly more fit! I might point to this thread when explaining this concept in the future, if you don't mind.

For the sex determination, I meant the plots in the CNV directory, these are the maypole plots from diagnostics/CNVcalls. Sorry! Hard to see which are the X and Y in the maypole plot, but good for the ploidy calls.

**Comment by kvaldez** [comment]
Hi Christoffer,

I reran superFreq with the new ploidy set to 3 for J3_T4, and was able to correct my copy number calls!  Yes, please feel free to use this as an example when explaining the feature. The corrected copy number summary plot: 

![summary](https://user-images.githubusercontent.com/19807160/72912400-93175000-3d09-11ea-9e1c-44119dba8021.png)

Regarding CNV plots, I accidentally uploaded the wrong files there, sorry about that.  Again I'm not super concerned about the incorrect sex determination if it doesn't negatively influence the outcome, but the correct CNV files from the original superFreq run are below.  J3_T1 was determined to be female, although to me the X and Y copy numbers look similar to the other samples:

![J3_norm](https://user-images.githubusercontent.com/19807160/72913004-82b3a500-3d0a-11ea-9190-959e1978c98b.png)
![J3_T1_cells](https://user-images.githubusercontent.com/19807160/72913005-82b3a500-3d0a-11ea-9569-3d7af589c06f.png)
![J3_T1](https://user-images.githubusercontent.com/19807160/72913006-82b3a500-3d0a-11ea-8df6-86eeaae71e8f.png)
![J3_T4_cells](https://user-images.githubusercontent.com/19807160/72913007-82b3a500-3d0a-11ea-869f-a214a93f2501.png)
![J3_T4](https://user-images.githubusercontent.com/19807160/72913008-82b3a500-3d0a-11ea-927e-9eea63179270.png)

Best,
Kristin

**Comment by ChristofferFlensburg** [comment]
Looks great, thanks for reporting back!
