### ISSUE TITLE
Error when running the file in the start of the GitHub page

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#5]
There is a problem in the "How do I run it?" section - 
`data = superfreq( ... normalCoverageDirectory=normalCoverageDirectory .... )`
`normalCoverageDirectory` does not exist. Should be `normalCoverageDirectory=""`, right?

**Comment by ChristofferFlensburg** [comment]
Oops, you are right, thanks.

This is a setting for when you have some reference normals that you want to use to filter SNVs, and other reference normals you want to use for comparing coverage. The reason to do this is that coverage analysis depends more on the reference normals being similar to the analysed samples, in terms of GC bias, capture regions, fragment length and so on, while the reference normals used to filter SNVs essentially only have to be aligned with the same aligner. So there are cases when you want to use a larger number of reference normals for SNV filtering, and a smaller subset for coverage analysis. The "normalCoverageDirectory" is the optional setting that separates the coverage normals from the others.

So if you don't want to use this option (which you don't in the typical case), you can just not use that option and it'll go to default where the same reference normals are used for both SNVs and coverage.

I removed that option from the example in the README, thanks.
