### ISSUE TITLE
Conda support

### ISSUE THREAD

**Issue by jabrennem** [ChristofferFlensburg/superFreq#51]
This is not so much an issue, but just a feature request. Any thoughts on creating a conda package for superFreq for faster installation?

**Comment by ChristofferFlensburg** [comment]
I realise that would be useful, but I don't have any experience in that area myself, so I don't see it happening anytime soon, sorry. Unless someone helps me set it up that is. You don't happen to know anyone that'd be willing to help me out? :o)

**Comment by jabrennem** [comment]
Thanks for replying! That's understandable. I would be interested in checking it out if you don't mind.

**Comment by ChristofferFlensburg** [comment]
I'd be very happy for you to have a go, and I'll support you to the extent I can. I did a 30 second search and found this site: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-r-pkgs.html, would this be a good place to start?

SuperFreq has samtools as a system requirement outside of R and depending on R packages, can that be built in?

Let me know what I need to do (explain as you would to a 5-year old please :D), and what can be done on your end.

**Comment by jabrennem** [comment]
Yeah! That's what I was following :) I was going to try and build it from scratch since I think the "conda skeleton cran" command expects it to be hosted from CRAN. There is already a bioconda package for samtools, so it's super easy to integrate it :D

**Comment by jabrennem** [comment]
@ChristofferFlensburg  Can I get you to create a git tag with the latest version of superFreq? 1.3.2 is perfect

**Comment by ChristofferFlensburg** [comment]
Ok, I think I made a tag for 1.3.2, my first tag ever! Thanks for taking me out of my comfort zone. :D It might've missed some changes in the README, but shouldn't affect running.

**Comment by jabrennem** [comment]
@ChristofferFlensburg I was able to create a working conda package locally. I created pull request with it. Feel free to pull it locally and try the build steps! Let me know if there are issues. #52

**Comment by ChristofferFlensburg** [comment]
Ohh, that looks super cool, thank you very much! :D 
And that was very fast, what's with the apologising for taking time! :P

I'll take it for a test, maybe also try running it on some test data, and let you know how it goes! If I can run it with my close to zero experience with conda, then I think anyone can!

**Comment by jabrennem** [comment]
Perfect! Let me know how the validation goes. It's probably best to validate it inside a conda environment so you know all the resources in that path are fit for superFreq. I believe it generates a tar.bz2 file depending on the os that builds it. I think it would need to be build for windows, linux, and mac for full compatibility. 

Once it's validated, you can upload the tar.bz2 file(s) to bioconda or your own channel. The benefit is that anybody with conda can could install with one line of code like this:

`conda install -c bioconda r-superfreq`

That would install install R, all the R bioconductor dependencies, samtools, etc.

To build off of that, if one needs an application that uses superFreq, gatk, and python 3.8, they could run

`conda install -c bioconda r-superfreq gatk4 python=3.8`
