### ISSUE TITLE
filtered mutations

### ISSUE THREAD

**Issue by mkinnaman** [ChristofferFlensburg/superFreq#58]
Hi Christof!

Is there a way to see why a certain mutation might have been filtered out. Comparing your pipeline to an alternative one and trying to reconcile why some mutations were called in the alternative pipeline but filtered out by superfreq.

Thanks!
Michael

**Comment by ChristofferFlensburg** [comment]
Hi, sorry I dropped the ball on this one. Is this issue still relevant?
Essentially you load the `allVariants.Rdata` into R, located in the R directory of the individual, and there you have data frames of all variants (as supplied by the input VCF) in all samples pre filters. Anything where `flag` column is not an empty string is filtered.
