### ISSUE TITLE
Working with b37 and not b19

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#6]
Hi,
I did all my analysis (mapping & variant calling) on b37 and not hg19. The only difference is the names of the chromosome (1 instead of chr1 etc).
Will that affect the run?

**Comment by ChristofferFlensburg** [comment]
SuperFreq should be able to handle both "3" or "chr3". Output will be in "3" format but there are checks that remove any "chr" in the input. Feel free to open a new issue if you run into problems related to this.
