### ISSUE TITLE
Does SuperFreq provide tumor purity?

### ISSUE THREAD

**Issue by dhsam30** [ChristofferFlensburg/superFreq#62]
Is there a way to find out tumor purity from SuperFreq results. Will this be in the somatics?

**Comment by ChristofferFlensburg** [comment]
Hi!

SuperFreq doesn't explicitly call a purity (we often find that concept a bit oversimplified with pre-cancer clones and more aggressive subclones), but you can look at the clonal tracking in the the river, and the purity will be the clonality of the largest cancer clone (maybe easier to look at page 2 for that). We find it often helps to look at the copy number plots as well for confirmation, as the main cancer clone often comes with large copy number alterations that can be called very reliably with accurate clonality. As for any analysis software, clonal tracking (including purity call) becomes more difficult for very quiet cancers with few mutations, and it can also become messy for heterogeneous cancers with very high CNA rates.

Let me know how it goes, good luck!
/Christoffer

**Comment by dhsam30** [comment]
Thanks Christoffer. I am seeing some varying results looking at the rivers plot for my simulated data. The truth doesn't seem to match with the clonality/purity value. Probably, I will use ASCAT, ControlFREEC or Sclust for getting the purity.

**Comment by ChristofferFlensburg** [comment]
I'd be interested in having a look at the results on your simulations otherwise. Always instructive to see results on others simulations, and maybe it can point to some potential imrpovements. You can email me flensburg.c at wehi.edu.au if you don't want to post publicly, or I totally get if you don't want to share at all. Good luck!
