### ISSUE TITLE
How to calculate clonal prevalence per clone?

### ISSUE THREAD

**Issue by KeyTals** [ChristofferFlensburg/superFreq#63]
Hi, 

I am trying to plot the clones using TimeScapes (http://bioconductor.org/packages/release/bioc/html/timescape.html) but not sure how to calculate the clonal prevalence. I was tying to take average of clonality per clone per case from river.xls but sum of total clonality of all clones is way more than 1 or 100% if i sum the average per clone.

Could you suggest better way to count it?

Thanks,
Keyur

**Comment by ChristofferFlensburg** [comment]
Hey Keyur,

You can get the clonalities (clonal prevalence) and the errors of each clone across samples from the saved Rdata.
That also includes the phylogentic structure as nested list with the germline clone at the top level. 
```
load('R/myIndividual/stories.Rdata')
clonalPrevalences = stories$stories$myIndividual$consistentClusters$cloneStories
phylogeny = stories$stories$GMTR19$consistentClusters$cloneTree
```
It's expected for clones to sum up to more than 1 if they are subclones of each other. For example the germline clone will be at 1 in all samples, so any somatic clone (that will be a subclone of the germline clone) will push it above 1. The unitarity restriction is that the **disjoint** subclones of a clone are not allowed to sum up to more than the containing clone in any sample. And that is enforced by superFreq within uncertainties, and is automatically used as a QC tool to identify noise clones that often violate that rule. So taking the phylogeny into account, you'll find that the clonal structure is consistent with unitarity within errors.

good luck, let me know how it goes,
Christoffer

**Comment by mkinnaman** [comment]
Keyur - were you able to figure out a work flow to create a timescape input?

**Comment by KeyTals** [comment]
Not yet, i admit i didnt much time to work on it but i did try from phylogeny tree, issue is still total sum = 1 for timescape

**Comment by ChristofferFlensburg** [comment]
Probably you'd need to parse the superFreq nested list `cloneTree` above, to turn it into whatever timescape wants as input to denote subclones. I guess timescape thinks they are all disjoint (giving the sum to 1 issue), so you need to find a way to tell it about subclone structures.
