### ISSUE TITLE
Calculating expected ranks; Error in if (floor(ranks[i]) < currentRank) next : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by gurujala1989** [ChristofferFlensburg/superFreq#64]
Hello,
I am new to superFreq algorithm. I am interested in looking for CNAs from RNAseq data of mine between cancer and normal samples. I have followed the R script from the superFreq manual. 

When I run my code, I get the following error:
"Calculating expected ranks...normalSample-normal..cancerSample-normal..Error in if (floor(ranks[i]) < currentRank) next :
  missing value where TRUE/FALSE needed"

Please let me know where am I doing it wrong. I really appreciate your help. 

Thanks!

**Comment by ChristofferFlensburg** [comment]
Hi!
That error message is not very informative unfortunately. I'd have to look at the logfile (located in the Rdirectory R/myIndividual/runtimeTracking.log) for clues. Maybe also let me know which version of R you are running on.

FYI, the logfile shows your metadata (but no germline variants), so only post if you are comfortable sharing that here. If you don't want to post your metadata publicly here, you can email it to flensburg.c at wehi.edu.au.

**Comment by gurujala1989** [comment]
Hello Christoffer,
Thanks for the reply. I have emailed you the logfile to your email with the same error issue as the subject title for the email. Could you please take a look at the email. Looking forward to hearing from you soon. 

Thanks!

**Comment by mlegarreta00** [comment]
Hello Christoffer, 
I am having the same issue as the person that opened this line and wanted to ask you for an email where I can send you the log file so that you can help me solve the error.
Thank you in advance!
