### ISSUE TITLE
LFC vs LFC-corrected and absolute copy number states

### ISSUE THREAD

**Issue by jeffstang** [ChristofferFlensburg/superFreq#66]
Hello Christoffer,

First off, thank you so much for developing a comprehensive tool with some form of standardization and provides functional QC metrics! As your paper had stated, it is definitely overwhelming coming into this field and having to make multitudes of tweaks across different tools for different purposes.. 

I have been using this workflow on my exome data and was just curious regarding the copy number conversion. I notice that in your outputs, there isn't an actual column for absolute copy number although the data visualization provides it. Just wanted to confirm since I dug through your source code whether this was a log2 based fold change and whether it is just a simple 2^log2(LFC) conversion. 

Additionally, I was slightly confused about the difference between the LFC column vs the LFC-corrected columns so I wanted some clarification regarding this as well. Also, in your paper, you had mentioned ploidy estimates as well if I remember correctly but I can't seem to find it in the data. Is there an under-the-hood metric that is calculated and then applied to on the LFC for it to be LFC-corrected? 

Thanks in advanced!
Jeffrey

**Comment by ChristofferFlensburg** [comment]
Hey!

Thanks, I'm happy someone is finding it useful!

The LFC (the "M" column in the output in plots/[individual]/data subdirectory) is the log2 LFC with respect to the reference normals, but shifted to take into account ploidy. There is some diagnostics on the ploidy calling in diagnostics/CNVcall and diagnostics/ploidy iirc.

The corrected LFC in the top-level tables is a bit of a legacy metric and maybe should be removed from the output. In one sentence it's a posterior version of the LFC, shrunk towards all the other LFCs with an empirical prior. It was something I played with as a way to provide a "best guess" to the actual LFC on gene level, but it is not being used by superFreq apart from in that output.

**Comment by jeffstang** [comment]
Got it. So for my use case, M would be the column of interest and to get absolute copy number, I convert back to an integer value via CN = 2^M? I think I should have clarified but as a follow up question, for plots/[individual]/differentRegions XLS files, this is where I observe the LFC and LFC_corrected columns. I immediately noticed some similarities to the plots/[individual]/data subdirectory/CNAbyGene TXT file but when I compared genes, some values were slightly off. Is this because of what you had described in terms of accounting for ploidy? 

Thank you for answering my questions, I really appreciate it!
Jeffrey

**Comment by ChristofferFlensburg** [comment]
Yes, copy number is 2 x 2^M (extra factor 2 for diploid normal).

data/CNAbyGene, M column should be corrected for ploidy, and width is the uncertainty. It may be that LFC in differentRegions.xls output is before the copy number calling and ploidy correction, so go with the data subdirectory if there are differences.

**Comment by jeffstang** [comment]
That makes sense.
Once again, thank you so much for the support!
Jeffrey
