### ISSUE TITLE
Replicability with Different Normal Samples

### ISSUE THREAD

**Issue by MatthewWiens101** [ChristofferFlensburg/superFreq#68]
Hi,

I am encountering an issue where my choice of normal samples heavily impacts the output of superFreq, and I would like to understand if this is expected or not. Specifically, if I include a female normal sample in addition to two male normal samples for a given tumor sample analysis, superFreq returns almost no CNVs, whereas it returns many CNVs using just the male normals. I am performing this combination because I have many female tumor samples which I would like to evaluate, but I have only one female normal. 

The superFreq manual seems to indicate that most any normal sample may be used so long as it is captured on the same machine in the same manner. In my case, the normal samples are wild type mice libraries from the same tissue origin as the tumors, so I imagine that they are closely related and should not feature any somatic SNPs. Would you expect that inclusion of a female wild type normal with male wild type normals could drastically affect the sensitivity of superFreq CNV detection? Maybe exclusion of the X/Y chromosomes in the BAM/CVF/fasta files might remedy this?

For reference, I have used Strelka with the RNA option for creating the VCFs, and I am using the 'RNA' mode in superFreq.

Thanks,

Matthew

**Comment by ChristofferFlensburg** [comment]
Hi Matthew,

Choosing reference normals for RNA-Seq analysis can be tricky, as there are so many sources of variability. SuperFreq estimates the variance between the reference normals, and the use those variance estimates to call CNAs. So if you only have two reference normals that are very similar to each other compared to the de-facto variability seen in the cancer sample, then you might underestimate the variance and thus over-call CNAs. Adding in a third reference normal that is more different from the others might give a more representative image of the variance in the cancer samples, and will reduce false calls. This might be what is happening to you.

I think it's safe to ignore the sex chromsomes in the CNA output from RNA, as they typically do not reflect the DNA copy number with the X silencing going on. I am not sure if the sex difference alone is enough to be a major difference in variance estimate, but it's possible.

There is quite a lot of diagnostics on this in plots/[individual]/diagnostics. Check for example the voom scatter plots, varianceBoost, the MA plots and the GC-bias plots in BSplots. Compare the two runs and see if you find any differences.

As we talk about in the RNA-Seq preprint (https://www.biorxiv.org/content/10.1101/2020.05.31.126888v1) CNA calling from RNA-Seq is only really reliable in larger regions >10Mbp or so, or ideally chromosome arm, and ideally with support from B-allele frequencies (as seen in the CNV directory, as well as maypole plots in diagnostics/CNVcalls and diagnostics MAFstat). If the calls you see are mostly small regions and no clear support from BAFs, then it's likely to be a case of underestimated variance. If the calls you see are large and supported by BAF, then you can probably trust them.

Hope I addressed your concern, and feel free to post some of the above diagnostics plots and I can comment more.

**Comment by bmeg310ubc** [comment]
Hi Christoffer,

Thanks for such a great explanation. I will try without sex chromosomes to see if that accounts for all of the increased variance, but its good to know that some of the results may be false due to similar normals. Also, thanks for sharing the RNA-seq preprint, I will be sure to read through it as I'm sure it will help greatly.

Matthew

**Comment by MatthewWiens101** [comment]
Hi Christoffer,

Thanks for such a great explanation. I will try without sex chromosomes to see if that accounts for all of the increased variance, but its good to know that some of the results may be false due to similar normals. Also, thanks for sharing the RNA-seq preprint, I will be sure to read through it as I'm sure it will help greatly.

Matthew
