### ISSUE TITLE
Error in parse(outFile) : 句法分析器1259行里不能有多字节字符

### ISSUE THREAD

**Issue by yanlina0205** [ChristofferFlensburg/superFreq#69]
When I install superFreq1.4.0 with R4.0.3, I meet the error below:
```
Error in parse(outFile) : 句法分析器1259行里不能有多字节字符
ERROR: unable to collate and parse R files for package 'superFreq'
```
But I can't find outFile

**Comment by ChristofferFlensburg** [comment]
Hey!

Seems the error is related to the multibyte character in the little easter egg I have in line 1259 of analyse.R:

```
#' shruggie
#'
#' @details ¯\_(ツ)_/¯
#'
#' @export
#'
#' @examples
#' cat("Sample quality is too low to tell if your favourite gene is mutated or not.", shrug(), '\n')
shrug = function() return("¯\\_(ツ)_/¯")


#' table flip
#'
#' @details (╯°□°)╯ ︵ ┻━┻
#'
#' @export
#'
#' @examples
#' cat("*** this analysis!!", tableFlip(), '\n')
tableFlip = function() return("(╯°□°)╯ ︵ ┻━┻")
```

I know it's generated warnings before, but seems it's actually producing errors now, so I removed it.
Try again.

**Comment by yanlina0205** [comment]
OK，thank you very much.The problem has been solved.But I have other errors:
E```
rror: package or namespace load failed for 'superFreq' in namespaceExport(ns, exports):
 undefined exports: shrug
错误: 载入失败
停止执行
*** arch - x64
Error: package or namespace load failed for 'superFreq' in namespaceExport(ns, exports):
 undefined exports: shrug
错误: 载入失败
停止执行
ERROR: loading failed for 'i386', 'x64'
* removing 'E:/R/R-4.0.3/library/superFreq'
错误: Failed to install 'superFreq' from GitHub:
  (由警告转换成)installation of package ‘C:/Users/bio_i/AppData/Local/Temp/Rtmpk5ARAj/file30a848d0411e/superFreq_1.4.2.tar.gz’ had non-zero exit status
```

**Comment by yanlina0205** [comment]
I have found why the error happened. That's because that you deleted the code up. I add them and installed the package succeedly.

**Comment by ChristofferFlensburg** [comment]
Right, I didn't recompile the package and only removed the code, not the entry in the namespace. I fixed that now, hopefully it should install properly now.
