### ISSUE TITLE
Downloading superFreq COSMIC annotation to superFreqResources/COSMIC

### ISSUE THREAD

**Issue by yanlina0205** [ChristofferFlensburg/superFreq#70]
The first run is Downloading superFreq COSMIC annotation to superFreqResources/COSMIC, and it needs to connect network. 
I want to know is  COSMIC annotation is downloaded everytime when I run superFreq？
And whether later steps need to connect network also? If not, how can I run the library with downloading the COSMIC annotation only once?

**Comment by ChristofferFlensburg** [comment]
Hey!

This is hidden in the `superFreq` documentation:

```
resourceDirectory: Character. The location of the directory where
          superFreq resources are located. Such as dbSNP, COSMIC,
          annotation. If the directory doesn't exist, it will be
          created and the data will be downloaded. Defaults to
          superFreqResources (in the directory where R is run).

```

So download happens only at the very start of the run, to ensure that the needed resources in the resourceDirectory  exists. If the resources already exist, no internet connection is needed. So you can do this once, and then make sure that future runs point to this directory from the first run and you will be 100% offline.

But note that the resources are different for hg19 and hg38 and mm10, exome vs genome etc, so if that changes between runs, some extra resources may need to be downloaded.

**Comment by yanlina0205** [comment]
Thank you！ I‘m sorry I didn't read the documentation carefully before, now I have solved the problem.
