### ISSUE TITLE
Mutation position concordance issue

### ISSUE THREAD

**Issue by gsiegwald** [ChristofferFlensburg/superFreq#73]
Hi Cristoffer,

I have an issue concerning the output of superfreq :

Looking at the "sample-river.tsv" file, we have a mutation in BRAF at the position "7:140753336" with AApos : 208, AAbefore : *	AAafter : R, isCosmicCensus : TRUE.

However at this nucleotide position, the AA position seems to be 600 and not 208 
( [https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=16673061](https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=166730618) )
would you have an idea why this is not concordant?

Thanks,

Guillaume

**Comment by ChristofferFlensburg** [comment]
Hey,

That'd be different transcripts of BRAF. SuperFreq picks the transcript with the most severe effect, and essentially a random one when there are ties. It is not aware of which is the canonical transcript of famous genes, so you sometimes see these shifts in AA positions wrt canonical mutations when a different transcript is used.

So if you want to look at mutations in a specific gene and compare to literature, it might be worth to take the genomic position and check that the AA numbers match up. With mismatches like yours, might want to run those through a different annotator that is aware of canonical transcripts. I think there are even online options. We used to use oncotator, and I think VEP has an online version as well.

**Comment by gsiegwald** [comment]
Hi,
Sorry for my delayed answer.
Thank you for this explanation, we will work with genomic positions with these cases.
