### ISSUE TITLE
symbolic links for normals bam

### ISSUE THREAD

**Issue by guillaume-rs** [ChristofferFlensburg/superFreq#76]
Hi,

When I use symbolic links for the normal bams in the normal/bams directory I encounter the following error :
```
Error in runDE(bamFiles, sampleNames, externalNormalCoverageBams, captureRegions,  :
  Error in featureCounts of normals.
Calls: superFreq -> superFreq -> analyse -> runDE
Execution halted
```
It works fine when I use hard links, but I wandering if it could work with symbolic links?

Thanks

**Comment by ChristofferFlensburg** [comment]
Hi!

It should work with soft links, and we're using that regularly ourselves. The error is in featureCounts (I think of the reference normals), which is the first place the BAM files are read from, so it could either be an issue with featureCounts (maybe something changed in recent version), it could be an error with how the reference normals are organised on your end, or there is a bug in how superFreq handles the metadata and paths to the bams.

To narrow down, have a look in the logfile, where it should say (pretty early on) which reference normal BAM files it identified. Check that those files are correct and can be read from.

If that seems to be in order, please send the logfile, and a sessionInfo(), and I'll have a look for more clues.

**Comment by guillaume-rs** [comment]
Hi,
Thank for the response, I think there are no problem with the normal bam files since it works with hard links. I've tested another time and I've got another error with the soft link :
[runtimeTracking.log](https://github.com/ChristofferFlensburg/superFreq/files/6142542/runtimeTracking.log)

**Comment by ChristofferFlensburg** [comment]
Hmm, in the logfile you sent it did do the counts from the reference normals, so files seem to be in order, and instead was an error on the later variant calling stage of the test samples. It's taking about 5mins to read from each exome which is about expected. The variant calling is using the index .bai files, while the read counting does not, so maybe double check that the index is in place. But I think it would have complained earlier if it couldn't find the index files...

The irregular behaviour makes me think that it might be out-of-memory. Maybe try decreasing cpus from 10 to 4 and run again. How much memory do you have available? Internally we request with 10GBs per cpu for exomes in our pipeline, which is a fair but more than needed for most samples, but it's quite variable depending on sample and experimental design, number of references etc.

Delete `~/superfreq/results/rerun_cfdna/sample_40_diag-529-634-795_mvf0.02/output/sample_40/variants.sample_40.Rdata` before you rerun, or superFreq might reuse the probably corrupt variants.

**Comment by guillaume-rs** [comment]
Thanks a lot for your comments, I will try with different cpus and RAM settings to see what happens (I have 2Tb of RAM available so it should be ok)

**Comment by ChristofferFlensburg** [comment]
You have more than enough memory then, so shouldn't be that (unless something has goner seriously wrong).

Other possibilities are issues with the .bai or with the .fa files, as they are not used in the read count step. I also see that your samtools version is a little bit old (1.3, current is 1.11), which may be prime suspect at this point, as I can't come up with anything better. I thought I had support for any 1+ version, but to be honest I haven't tested on anything earlier than 1.9 or so in a long time.

**Comment by guillaume-rs** [comment]
Updating samtools to the latest version actually solved this problem :)
