### ISSUE TITLE
Error in featureCounts

### ISSUE THREAD

**Issue by UmairAhmadKhan97** [ChristofferFlensburg/superFreq#78]
Hello,

I am currently working with whole genome tumor sample pairs and I am getting an error from featureCounts, where the execution halts due to an error with paired-ends detected in single read library thus no counts being generated. I have ensured that the bam files come from the correct reference and that the genome is hg38 in the superFreq function call. Since I have 5 different samples, I am running each in a separate batch job and at 12 CPUS with 200GB memory allocated. The preliminary variant call worked fine for the bams but the featureCounts results in an error. Would I need to manually update the function to handle this since it seems that it doesn't even consider paired-ends based on the below featureCounts settings(highlighted)? Or does this have to do with not providing capture regions, although whole genome sequencing is being used? Some help on ways to proceed would be much appreciated!

superFreq version 1.4.2
Rsubread version 2.4.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 3 BAM files                                      ||
||                                                                            ||
||                           363-germ_S5.final.bam                            ||
||                           363-pretx_S14.final.bam                          ||
||                           363-prog_S15.final.bam                           ||
||                                                                                               ||
||              **Paired-end : no**                                                       ||
||        **Count read pairs : no**                                                   ||
||              Annotation : R data.frame                                     ||
||      Dir for temp files : .                                                ||
||                 Threads : 12                                               ||
||                   Level : feature level                                    ||
||      Multimapping reads : counted                                          ||
|| Multi-overlapping reads : counted                                          ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

ERROR: Paired-end reads were detected in single-end read library : /gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/Sample_363-germ_S5/compbio/analysis/363-germ_S5.final.bam
No counts were generated.
Error in featureCounts.

**Comment by UmairAhmadKhan97** [comment]
Hello,  I apologize for this, just saw another issue that handles this. I'll try that.

**Comment by ChristofferFlensburg** [comment]
Yep, that looks like the issue that triggered the latest update a few weeks ago. I realise I didn't actually update superFreq version for that push though... 😬 I'll sort that out next push.
 
Anyway, if you get the latest version of superFreq and still get this error, feel free to re-open the other issue and I'll have a look.

**Comment by UmairAhmadKhan97** [comment]
Thank you for the update Christoffer. Things seem to be running well right now as my test sample seems to be running fine. I'm hoping this avoids memory issues due to filling up the cache as you mentioned. Also, it seems that running at lower number of CPUS also avoids memory allocation issues as I had problems running at 16 CPUS vs 12 in the initial variant call. Thanks!!
Umair    On Sunday, March 21, 2021, 06:31:40 PM PDT, Christoffer Flensburg ***@***.***> wrote:  
 
 


Yep, that looks like the issue that triggered the latest update a few weeks ago. I realise I didn't actually update superFreq version for that push though... 😬 I'll sort that out next push.

Anyway, if you get the latest version of superFreq and still get this error, feel free to re-open the other issue and I'll have a look.
