### ISSUE TITLE
Memory Issues 

### ISSUE THREAD

**Issue by UmairAhmadKhan97** [ChristofferFlensburg/superFreq#79]
Hi, 

I am running a test sample on whole genome sequencing data for a tumor-normal sample and I believe the pipeline is nearly complete, however, it keeps breaking due to bus errors and out of memory issues. The first time I ran the pipeline I set my batch script with 12 CPUS and 160 or 180G of memory. Then I noticed I got an error where memory cannot be allocated, so I decided to reduce the number of CPUS to 10 with 120G of memory as I ran the batch script once again. 

So I understand the pipeline saves checkpoints for me able to run the batch script again without restarting everything, but I am a bit unsure on how to proceed in dealing with these memory issues. I ran only one sample so far in hopes to use the positions examined in the 5 germline/normals samples I have for my other samples which I will run all together in different jobs,(as mentioned in another issue as cache will be used) so is there any long term solution or would I need to keep playing around with the memory allocation? 

All positions are examined already for the bam files for the normals and the cancer samples. The memory issues are resulting after these steps. My thoughts are that there may be too much cache on the environment and thus that is causing memory issues, however, it seems that cache may be able to help speed up other sample runs so I wouldn't want to get rid of that.
Are there any large files that are generated that are safe to remove to be able to allow more memory to be allocated while not interfering with any saved cache that can be used for later samples? Any help would be much appreciated! Please let me know if you need any more information!

Thanks,
Umair 

free command output:
                      total        used        free      shared  buff/cache   available
Mem:        7990288      997040      333836       89440     6659412     6494248
Swap:             0           0           0

Errors:
First Run Error:

2021-03-22 11:17:28 (1.15 MB/s) - ‘/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/R/Sample_144/hg38genome.10k.named.dn.bed’ saved [18231704/18231704]

Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: superFreq ... FUN -> unlist -> mclapply -> lapply -> FUN -> mcfork
In addition: Warning messages:
1: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 24 out-of-bound ranges located on sequences 1,
  2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, X, and Y. Note that ranges located on a sequence whose length is
  unknown (NA) or on a circular sequence are not considered out-of-bound
  (use seqlengths() and isCircular() to get the lengths and circularity
  flags of the underlying sequences). You can use trim() to trim these
  ranges. See ?`trim,GenomicRanges-method` for more information.
2: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 48 out-of-bound ranges located on sequences 1,
  2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, X, and Y. Note that ranges located on a sequence whose length is
  unknown (NA) or on a circular sequence are not considered out-of-bound
  (use seqlengths() and isCircular() to get the lengths and circularity
  flags of the underlying sequences). You can use trim() to trim these
  ranges. See ?`trim,GenomicRanges-method` for more information.
3: In plot.new() :
  Cannot open temporary file '/tmp/RtmpwB5DWN/pdfb72a2113a518' for compression (reason: No such file or directory); compression has been turned off for this device
4: In plot.new() :
  Cannot open temporary file '/tmp/RtmpwB5DWN/pdfb72a1f1a37f5' for compression (reason: No such file or directory); compression has been turned off for this device
5: In plot.new() :
  Cannot open temporary file '/tmp/RtmpwB5DWN/pdfb72a5766d9' for compression (reason: No such file or directory); compression has been turned off for this device
6: In plot.new() :
  Cannot open temporary file '/tmp/RtmpwB5DWN/pdfb72a4d165741' for compression (reason: No such file or directory); compression has been turned off for this device
7: In plot.new() :
  Cannot open temporary file '/tmp/RtmpwB5DWN/pdfb72a39b44b6b' for compression (reason: No such file or directory); compression has been turned off for this device
Execution halted
Error while shutting down parallel: unable to terminate some child processes

Second Run Error with new batch job parameters:

The following object is masked from ‘package:limma’:

    plotMA

The following object is masked from ‘package:BiocGenerics’:

    plotMA

 *** caught bus error ***
address 0x7f9c23e27c43, cause 'non-existent physical address'

 *** caught bus error ***
address 0x7f9c23e27c43, cause 'non-existent physical address'

 *** caught bus error ***
address 0x7f9c23cdaba5, cause 'non-existent physical address'

 *** caught bus error ***
address 0x7f9c23ee8a00, cause 'non-existent physical address'
/var/spool/slurmd/job12077690/slurm_script: line 6: 199642 Segmentation fault      R --file=superFreq.R --args $1 $2 > superfreq_log2_$1.out

Traceback:
 1: which(abs(flagXchr - x) < 1000)
 2: FUN(X[[i]], ...)
 3: lapply(X = S, FUN = FUN, ...)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 8: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
 9: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
10: FUN(X[[i]], ...)
11: lapply(seq_len(cores), inner.do)
12: mclapply(q$x[chrI], function(x) {    within1000 = which(abs(flagXchr - x) < 1000)    within300 = which(abs(flagXchr[within1000] - x) < 300)    within200 = which(abs(flagXchr[within300] - x) < 200)    within100 = which(abs(flagXchr[within200] - x) < 100)    return(length(within100) >= 10 | length(within200) >= 20 |         length(within300) >= 30 | length(within1000) >= 50)}, mc.cores = cpus)
13: unlist(mclapply(q$x[chrI], function(x) {    within1000 = which(abs(flagXchr - x) < 1000)    within300 = which(abs(flagXchr[within1000] - x) < 300)    within200 = which(abs(flagXchr[within300] - x) < 200)    within100 = which(abs(flagXchr[within200] - x) < 100)    return(length(within100) >= 10 | length(within200) >= 20 |         length(within300) >= 30 | length(within1000) >= 50)}, mc.cores = cpus))
14: FUN(X[[i]], ...)
15: lapply(variants$variants, function(q) {    flagX = q$x[q$flag != "" & q$flag != "Nr"]    chrs = xToChr(flagX, genome)    for (chr in unique(chrs)) {        flagXchr = flagX[chrs == chr]        chrI = which(xToChr(q$x, genome) == chr)        inNoisyRegion = unlist(mclapply(q$x[chrI], function(x) {            within1000 = which(abs(flagXchr - x) < 1000)            within300 = which(abs(flagXchr[within1000] - x) <                 300)            within200 = which(abs(flagXchr[within300] - x) <                 200)            within100 = which(abs(flagXchr[within200] - x) <                 100)            return(length(within100) >= 10 | length(within200) >=                 20 | length(within300) >= 30 | length(within1000) >=                 50)        }, mc.cores = cpus))        q$flag[chrI[inNoisyRegion]] = paste0(q$flag[chrI[inNoisyRegion]],             "Nr")    }    catLog(" ", sum(q$flag[chrI] == "Nr"), sep = "")    return(q)})
16: lapply(variants$variants, function(q) {    flagX = q$x[q$flag != "" & q$flag != "Nr"]    chrs = xToChr(flagX, genome)    for (chr in unique(chrs)) {        flagXchr = flagX[chrs == chr]        chrI = which(xToChr(q$x, genome) == chr)        inNoisyRegion = unlist(mclapply(q$x[chrI], function(x) {            within1000 = which(abs(flagXchr - x) < 1000)            within300 = which(abs(flagXchr[within1000] - x) <                 300)            within200 = which(abs(flagXchr[within300] - x) <                 200)            within100 = which(abs(flagXchr[within200] - x) <                 100)            return(length(within100) >= 10 | length(within200) >=                 20 | length(within300) >= 30 | length(within1000) >=                 50)        }, mc.cores = cpus))        q$flag[chrI[inNoisyRegion]] = paste0(q$flag[chrI[inNoisyRegion]],             "Nr")    }    catLog(" ", sum(q$flag[chrI] == "Nr"), sep = "")    return(q)})
17: newFlagFromNormals(variants, normalVariants, genome, RNA = RNA,     cpus = cpus, correctReferenceBias = correctReferenceBias)
18: matchFlagVariants(variants, normalVariants, individuals, normals,     genome, Rdirectory, flaggingVersion = flaggingVersion, RNA = RNA,     cpus = cpus, byIndividual = byIndividual, rareGermline = rareGermline,     forceRedoMatchFlag = forceRedoMatchFlag, cosmicDirectory = cosmicDirectory,     cosmicSalvageRate = parameters$cosmicSalvageRate)
19: analyse(inputFiles = inputFiles, outputDirectories = outputDirectories,     settings = settings, forceRedo = forceRedo, runtimeSettings = runtimeSettings,     parameters = parameters, byIndividual = T, manualStoryMerge = manualStoryMerge,     correctReferenceBias = correctReferenceBias, vepCall = vepCall,     resourceDirectory = resourceDirectory, mode = mode, filterOffTarget = filterOffTarget,     rareGermline = rareGermline, annotationMethod = annotationMethod,     ploidyPriors = ploidyPriors)
20: superFreq(metaDataFile = input$metaDataFile, captureRegions = captureRegions,     normalDirectory = normalDirectory, Rdirectory = input$Rdirectory,     plotDirectory = input$plotDirectory, reference = reference,     genome = genome, BQoffset = BQoffset, cpus = cpus, outputToTerminalAsWell = outputToTerminalAsWell,     forceRedo = forceRedo, normalCoverageDirectory = normalCoverageDirectory,     systematicVariance = systematicVariance, maxCov = maxCov,     cloneDistanceCut = cloneDistanceCut, resourceDirectory = resourceDirectory,     mode = mode, splitRun = F, correctReferenceBias = correctReferenceBias,     vepCall = vepCall, filterOffTarget = filterOffTarget, rareGermline = rareGermline,     exacPopulation = exacPopulation, cosmicSalvageRate = cosmicSalvageRate,     annotationMethod = annotationMethod, ploidyPriors = ploidyPriors,     participants = participant)
21: superFreq(metaDataFile = "/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/metaData.tsv",     genome = "hg38", normalDirectory = "/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/superFreq/myReferenceNormals/bam",     Rdirectory = "/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/R",     plotDirectory = "/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/plots",     reference = "/gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/reference/GRCh38_full_analysis_set_plus_decoy_hla.fa",     mode = "genome", cpus = cpus, participants = participant)
An irrecoverable exception occurred. R is aborting now ...
slurmstepd: error: Detected 293 oom-kill event(s) in StepId=12077690.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by ChristofferFlensburg** [comment]
Hey!

Yeah those specs are a bit on the limit for genomes.
The parts of the memory you can somewhat easily affect are:

- roughly linearly with cpus
- roughly linearly with the total number of unique positions in the vcf input.
- roughly linearly with number of samples, from the individual plus the reference normal samples

I am running tests on human genomes, a cancer-normal with two reference normals (so total 4 samples), 5.9M positions from the VCFs with 10 cpus and 200GBs, and that works fine. The memory read outs in the logs (`Rdirectory/myIndividual/runtimeTracking.log`) go up to 6.6GB, which is then multiplied by number of cpus when branching, and who knows how much overhead from system etc on top of that...

So options are:
- Decreasing cpus further

- Limit number of reference normals. Genomes are typically much cleaner and less variable than exomes, so fewer references are fine. I think 3 is plenty unless there are batch effects or QC issues, and running on the minimum allowed of 2 works fine for my test data.

- Pre-filter the input VCF files. Variants supported by 2 or fewer reads are unlikely to be very interesting for example, and might remove a lot of noise variants without having them read into R memory.

The cache is written to file, and will be loaded instead of read from the BAM, so should only save time. The cache shouldn't affect memory, or it might decrease it during the reading from BAM phase. However, if you change the set of reference normal you will have to delete the corresponding cache in the `R` directory in the reference normal directory. Similarly if you change the input VCF files, you have to delete all the saved files in `Rdirectory/myIndividual` that is called anything with "positions" or "variants". May as well delete it all and be safe. :D

Let me know how it goes!

**Comment by UmairAhmadKhan97** [comment]
Hey Christoffer, thank you for your thoroughness and quick response! I'll try these solutions out and keep you updated.

**Comment by ChristofferFlensburg** [comment]
Sounds good. Memory useage is a common issue, so I added the suggestions to the README. Probably should have done that a while ago...

**Comment by UmairAhmadKhan97** [comment]
Hey Christoffer,

Just wanted to share some things. After looking at the variant read distribution, I decided to remove variants that had less than 3 reads, although even after, the highest frequency of reads supporting variants ranges from 3-6 reads. So for the third option you have mentioned above, I am thinking maybe to filter VCFs even more, although I do wish to include low variant allele frequencies in the analysis. Second, I also ran with 10 CPUS at 200G, and stuck with 3 normal references after comparing box plots of read depth and variant read distribution where I felt that there was no drastic batch effects or bias. Below shows the point at which the memory gives up. Currently after doing the above, there are 7155319 positions being examined in the bam files. 

Examining 7155319 positions from /gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/Sample_144-prog_S7/compbio/analysis/144-prog_S7.final.bam in 7156 batches.

Number of variants for normal references are 5894260, 6043696, and 5799974 respectively and superFreq is examining 7155319 positions for the bams. 

I'm currently thinking to do some more filtering for the VCF files and using only 2 reference normals.  Note I'm a newbie so I'd have to figure out the best way to filter VCFs while trying to account for low variant allele frequencies. 

I just wanted to ask if further filtering VCFs and only using 2 reference normals would be the correct way to proceed. Would appreciate any thoughts you may have. Thank you!

2021-03-28 14:34:21 
Current memory use (Mb): 629.1, max use (Mb): 629.1
Starting differential coverage analysis by sample.
Loading saved differential coverage results.
Loaded saved differential coverage results
2021-03-28 14:34:24 
Current memory use (Mb): 742.2, max use (Mb): 742.2
Plotting volcanoes to /gpfs/commons/groups/landau_lab/team_CLL/Celgene_project/plots/Sample_144/volcanoes/..done!
2021-03-28 14:34:25 
Current memory use (Mb): 742.3, max use (Mb): 742.3
Using variants by individual.
Loading saved variants by individual.
Loading saved variants by individual.
Matching 13806442 against 13806442 variants..to 13806442 variants.
Matching 13806442 against 13806442 variants..to 13806442 variants.
Flagging variants with large minor variants: 205 ..41 ..21 ..Flagging variants with large minor variants: 211 ..183 ..193 ..Keeping 8549919 out of 13806442 (61.9%) SNVs that are present at 5% frequency in at least one sample.
Average variant loss is 0.04910869 
Flagged 1860315 out of 8549919 variants that are recurrently and consistently noisy in normals.
Flagged another 446214 out of 8549919 variants that are not db, but significantly present in at least one normal sample.
Flagged another 33317 out of 8549919 variants that have a coverage ten times higher than median 41.33333  in the normals.
Flagging variants not above normal background level: 438710..420535..414217..Flagged 52843 out of 2798349  non-db variants that are consistently polymorphic in normals.
Flagging SNPs that are in noisy regions. New flags by sample:

**Comment by ChristofferFlensburg** [comment]
Hey!

Hmm, it say's there are 7M positions, but then loads in 14M variants. It's normal to have a few more variants than positions (by finding multiple variants in the same position), but factor 2 is more than expected. Maybe it's reusing the old (larger number of) variants? So first make sure that was rerun properly. Delete .Rdata files, or look at the `forceRedo` option to `superFreq()`, or rerun in a completely new plots and R directory for full reset.

If that's not it, and you can't come up with good ways to further filter the VCFs, drop down more in cpus or go down to two reference normals.

Also I don't know how many samples you are analysing.

**Comment by UmairAhmadKhan97** [comment]
Hey Christoffer, thanks for checking the problem out. I think there is a problem with loading the variants here because I reran my batch job with an updated number of CPUS after it had failed without the forceRedo as well as not deleting any type of files, so I think you're right that it may be reusing old data. Regardless, I reran again only considering high quality SNPs (GQ > 20) so I hope that goes through but I'll refer to this if problems do arise. Thank you!

**Comment by UmairAhmadKhan97** [comment]
Hey Christoffer, so my test run with WGS ended up with way too many mutations(which is expected) for which I am switching to exome mode; I am glad that it ran although the job timed out though because I set a strict limit for a little more than 24 hours, though it was able to create the summary pdf which is great! I'm assuming providing aligned bams for WGS would not be compatible with exome mode? Or does this depend on the capture regions?  Currently I'm thinking about doing the following:

1. Use genome mode and provide capture regions of whole exomes with WGS bams(Assuming this would only use the target intervals for mutation calls)
2. Use exome mode and provide capture regions of whole exomes with WGS bams

The second option creates a bunch(100+) of tmp files in my working directory and seems to get stuck or is just taking a while to run which would be fine. 

Is there an ideal way to do use WGS bams to target mutations in exomes? This sounds hacky and I should just use the tool as intended but if you have any thoughts that would be much appreciated! Thanks.

Umair

**Comment by UmairAhmadKhan97** [comment]
Using genome mode and providing capture regions extracts the exome variants from the bams, but the capture regions utility seems deprecated; I installed and loaded seqinr as mentioned below at the first warning message. Using exome mode without capture Regions(assuming this would be default) creates a massive amount of temp files similar to what I said above which seems erroneous though I could be wrong. Is this behavior expected?

I was thinking to use the default capture regions by not having the captureRegions parameter in the superFreq function call and run the WGS bams in exome mode, except it creates the tmp files and also seems to take unusual time getting exome variants from the bams compared to when I ran in genome mode with captureRegions. Any thoughts? I'm thinking the bed file I provided maybe inappropriate as well. 
 
Using genome mode with my captureRegions with library(seginr)
Error in plot.window(...) : need finite 'ylim' values
Calls: superFreq ... plotColourScatter -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In importReferenceGenome(file = fastaFile) :
  Custom capture regions are deprecated, and this run might crash soon. (If it goes through, great, ignore this.) Leave the captureRegions parameter as default and appropriate pre-annotated capture regions will be downloaded. Alternatively, if you really want to use custom captureRegions, (install and) load the seqinr package and try again. No guarantees though. Good luck!
2: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1193 out-of-bound ranges located on sequences
  3, 5, 7, 17, 18, 20, and X. Note that ranges located on a sequence
  whose length is unknown (NA) or on a circular sequence are not
  considered out-of-bound (use seqlengths() and isCircular() to get the
  lengths and circularity flags of the underlying sequences). You can use
  trim() to trim these ranges. See ?`trim,GenomicRanges-method` for more
  information.
3: In valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE) :
  GRanges object contains 1193 out-of-bound ranges located on sequences
  3, 5, 7, 17, 18, 20, and X. Note that ranges located on a sequence
  whose length is unknown (NA) or on a circular sequence are not
  considered out-of-bound (use seqlengths() and isCircular() to get the
  lengths and circularity flags of the underlying sequences). You can use
  trim() to trim these ranges. See ?`trim,GenomicRanges-method` for more
  information.

**Comment by ChristofferFlensburg** [comment]
Ohh, right...

When running in genome mode, superFreq switches off paired end counting, as it requires featureCounts to re-sort the BAM file. Resorting a RNA-Seq or exome doesn't take too long, but is prohibitive for genomes and creates all the temp-files, I assume featureCounts uses a divide and conquer sorting algorithm.

So when running on a genome in exome mode, superFreq doesn't tell featureCounts to ignore read pairs, and then you get this issue... Oof.

I need to make a "genomeAsExome" mode or something, that runs as an exome, but doesn't use read pairs in featureCounts. It'll have to be next week though, sorry, I'm a bit busy these days.

If you want to do it yourself, you can hack it by just searching the code for the `isPairedEnd=` setting in featureCounts (it'll be in runDEexon), and set it to FALSE everywhere. Then run again as exome. That version will ignore paired ends in exomes and RNA-Seq as well, but honestly I doubt that will impact accuracy noticeably.

**Comment by UmairAhmadKhan97** [comment]
I see, thanks. I'll consider hacking it. 

Since I wasn't sure if the initial capture regions I had from the Broad Institute was working(Error: Using genome mode with my captureRegions with library(seginr);Error in plot.window(...) : need finite 'ylim' values) I decided to use UCSCs hg38 exon intervals. So I can see that only exome positions in the bam would be called, but I hope that won't recreate the error above. 

Is running genome mode with the custom capture region problematic overall ? If so I'd probably cancel the job I'm running right now and use the hack you mentioned. Thanks!!

**Comment by UmairAhmadKhan97** [comment]
Alright the results from the above approach are looking really nice. Thanks for you help!
