### ISSUE TITLE
Making summary plot..Error in if (sum(use) == 0) next : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by gilhornung** [ChristofferFlensburg/superFreq#8]
Got this error:

```

Tracking clonal evolution in WS9..Found 116 somatic SNVs to track.
SNVs..
Filtered 18 small, 13 uncertain, 4 indel and 0 present in normal stories.
Keeping 81 SNV stories.
Tracking clonal evolution in CNVs..208 regions..208 events.
Extracting stories, comparing SNP shift directions..84 overlapping stories filtered..Filtered 129 small, 31 uncertain, 61 small region and 50 present in normal stories.
Filtered 1 stories that are potentially based on false SNPs.
Keeping 52 CNV stories.
merge events into clones..got 11 stories...decide subclone structure..removing inconsistent dodgy clones..got 6 consistent stories...Found 181 somatic SNVs to track.
Found 0 rare germline variants to track.
Filtered 3 present in normal stories.
208 regions..208 events.
Extracting stories, comparing SNP shift directions..84 overlapping stories filtered..done!

Marking SNV that behave like germline SNPs..done!
Saving stories..done!


Plotting SNP progression to /gpfs/units/bioinformatics/projects/Sheba/MayaDadiani/INCPMPM-1568/analysis/batch2/ppl_b37/run8-superFreq/plots/WS9/multiSample/WS9.pdf...
Finding common variants..Finding common variants..Finding common variants..Finding common variants..Finding common variants..Finding common variants..done.
Making summary plot..Error in if (sum(use) == 0) next : missing value where TRUE/FALSE needed
In addition: There were 20 warnings (use warnings() to see them)

\> warnings()
Warning messages:
1: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
2: In system(call, intern = T) :
  line 8 may be truncated in call to system(, intern = TRUE)
3: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
4: In system(call, intern = T) :
  line 8 may be truncated in call to system(, intern = TRUE)
5: In system(call, intern = T) :
  line 9 may be truncated in call to system(, intern = TRUE)
6: In system(call, intern = T) :
  line 10 may be truncated in call to system(, intern = TRUE)
7: In system(call, intern = T) :
  line 7 may be truncated in call to system(, intern = TRUE)
8: In system(call, intern = T) :
  line 8 may be truncated in call to system(, intern = TRUE)
9: In system(call, intern = T) :
  line 9 may be truncated in call to system(, intern = TRUE)
10: In rareGermline | somatic :
  longer object length is not a multiple of shorter object length
11: In rareGermline | somatic :
  longer object length is not a multiple of shorter object length
12: In rareGermline | somatic :
  longer object length is not a multiple of shorter object length
13: In rareGermline | somatic :
  longer object length is not a multiple of shorter object length
14: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
15: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
16: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
17: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
18: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
19: In qualityProgression(variants$variants[ts], variants$SNPs,  ... :
  found NA somaticQ in qs of quality progression plot.
20: In .Method(..., deparse.level = deparse.level) :
  number of rows of result is not a multiple of vector length (arg 2)

```

**Comment by ChristofferFlensburg** [comment]
Hey!

Thanks for reporting. It seems like it went through the analysis with warnings only, and then stopped at the start of the output phase. Probably something went wrong at an earlier stage, but crashed only later, and I'm not sure what it was. From what I see it seems related to the VEP annotation, but not 100% sure. I think I'd need to have a look at the log file (in the R directory, runtimeTracking.log). The logfile contains your  metadata (but not your actual data), so if you don't feel comfortable having that public you can send it to me in an email to me instead at flensburg.c@wehi.edu.au, as you want.

cheers
/Christoffer

**Comment by ChristofferFlensburg** [comment]
I had a look at what you sent, and it turned out to be a corner case that messed up the VEP output parsing:

The normal sample get only one variant sent to VEP for annotation, an A to T SNV, so the VEP output is only a few lines with that variant annotated against a few different TERT transcripts. They all all have “T” in the variant column of course. Turns out that when you read in that file into R with read.table(), it interprets the column with only “T” as a logical TRUE, not a character “T”. This then confuses superFreqs downstream parsing to no end (thinking it’s a “TRUE” variant), and it ended up with a new variant (present in the normal sample only) insertion of “+RUE” at that location, which kindof makes sense in a way. :P And then further downstream the normal sample has an extra variant in the list, which triggered the “not same length” warnings, and finally crashed a comparison between two vectors of different length in the plotting.

Anyway, I told read.table that the columns are all of “character” class in this case, so that should fix it… It’ll be part of next version.

**Comment by gilhornung** [comment]
What a crazy bug!
Thanks for the help. Is this in the git already? Can I pull it?

**Comment by ChristofferFlensburg** [comment]
It's not on online yet. I am working on a bit larger version and it'll come with that. It's just tiny change, so you can do it yourself if you want it now.

Change

VEPdata = try(read.table(VEPfile, fill=T, header=F), silent=T)

to 

VEPdata = try(read.table(VEPfile, fill=T, header=F, colClasses='character'), silent=T)

in two places in runVEP.R. That's completely untested so far, but "should" work. :P

**Comment by gilhornung** [comment]
Ok, I tweaked it locally and it worked perfectly.
I am closing the issue.
