### ISSUE TITLE
Hi Christoffer, I was wondering how to get B allele frequency from the characterized SNPs

### ISSUE THREAD

**Issue by YuehuiZ** [ChristofferFlensburg/superFreq#80]
Hi Christoffer, 

I am a fresh learner to use SuperFreq to analyze my data. I was wondering how to get B allele frequency from the characterized SNPs? May I also ask if I can get each SNP's copy number log2ratio? Thank you very much for your help.

Warm regards,
Yuehui

**Comment by ChristofferFlensburg** [comment]
Hey!

The raw data is in the R directory `Rdirectory/myIndividual/*.Rdata`, and it's all in R format, so you need to be familiar with that. For variants in general, look at allVariants.Rdata, for copy number calling, look at clusters.Rdata. If you look at the manual PDF that should be somewhere here on github, there should be descriptions of what these objects are.

In your case, the BAFs are in something called `eFreqs` (for effective frequencies) that's roughly the read counts of the BAFs. The log2ratio (M column) is done by gene in the `CR` (for Capture Regions), so not specific to each BAF as in a SNP-array.

There are also by-gene summaries if you look in the plots directory, in `data` subdirectory, where the variant and total read depth have been summed within each gene.

Let me know if you can't find what you're looking for.
good luck!

**Comment by YuehuiZ** [comment]
Hi Christoffer,

Got it. Thank you for your help.

Warm regards,
Yuehui
