### ISSUE TITLE
CNA calls in the output

### ISSUE THREAD

**Issue by zozcan89** [ChristofferFlensburg/superFreq#86]
Hi, 

Could you please tell me which output file to look at to get the CNA locations, e.g. chr1 1,000,000 2,000,000 gain (like a bed file)? Thank you.

Best regards,

**Comment by ChristofferFlensburg** [comment]
Plot directory, data subdirectory, the files with "segment" have the segment information. "call" column has the genotype, so AB for normal two copies heterozygous, A for loss, AAB for gain, AA for CNN LOH, etc.
