### ISSUE TITLE
Capture regions read

### ISSUE THREAD

**Issue by arpanda** [ChristofferFlensburg/superFreq#91]
As `wget` download is not working, I have downloaded the capture files and kept in the resource and individual directories and now its not giving me the error related to the download, but getting the below error.

```
Normal bamfiles are:
<bam path>
<bam path>
Loading capture regions...Error in read.table(bsFile, fill = T, quote = "") :
  no lines available in input
Calls: superFreq ... superFreq -> analyse -> importCaptureRegions -> read.table
Execution halted
```
As the location of `bsFile` is not shown in the error, I am not able to get, which file it's looking for to solve it by own. Therefore, could you please guide me to solve the issue. 

Also, in the error log, is it possible to add the location of `bsFile`?
 
Thanks
 Arijit

**Comment by ChristofferFlensburg** [comment]
Yeah the capture region bed files are a bit different. This is a remnant of when superFreq used to support user-provided capture regions, and they were stored and processed in a different way. it's all automated now, but the expect file location is still different from other resources, for no real reason at this point... Another thing I probably should update. 😬 

There are three expected files, *.bed, *.named.bed and *.named.dn.bed, that are expected to be in each subdirectory of the `Rdirectory` of each individual, so `myRdirectory/myIndividual/hg19exons.*.bed` if you are running on hg19 exomes. So three .bed files for each INDIVIDUAL in your meta data, that will each get it's own `myRdirectory/myIndividual` subdirectory. The base name of the bed depends on your `mode` and `genome` according to this:

```
downloadCaptureRegions = function(directory, genome='hg19', mode='exome', binSize=10000) {
    url = ''
    if ( genome == 'hg19' & mode %in% c('exome', 'RNA') )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/hg19exons.bed'
    if ( genome == 'hg38' & mode %in% c('exome', 'RNA') )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/hg38exons.bed'
    if ( genome == 'mm10' & mode %in% c('exome', 'RNA') )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/mm10exons.bed'

    if ( genome == 'hg19' & mode == 'genome' & binSize == 10000 )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/hg19genome.10k.bed'
    if ( genome == 'hg38' & mode == 'genome' & binSize == 10000 )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/hg38genome.10k.bed'
    if ( genome == 'mm10' & mode == 'genome' & binSize == 10000 )
        url = 'http://gitlab.wehi.edu.au/flensburg.c/superFreq/raw/master/captureRegions/mm10genome.10k.bed'

    if ( url == '' ) {
        catLog('\nERROR: Couldnt find any capture regions for genome ', genome, ' in mode ', mode, ' with binSize ', binSize, '\n\n')
        stop('Couldnt find any capture regions for genome ', genome, ' in mode ', mode, ' with binSize ', binSize)
    }
    
    urls = c(url, gsub('.bed$', '.named.bed', url), gsub('.bed$', '.named.dn.bed', url))
    for ( url in urls ) {
      destFile = paste0(directory, '/', basename(url))
      if ( !file.exists(destFile) ) download.file(url, destfile = destFile, method="wget")
    }

    return(paste0(directory, '/', basename(urls[1])))
}
```

So you need to download those three files and copy the to all the R subdirectories. I hope that should solve it.

I'm sorry this is messy. It was never meant to have to be manually downloaded, but people run into troubles so often that I really should streamline the process of manual download.

**Comment by arpanda** [comment]
I am using `mm10` reference genome and have few RNAseq samples. So, I am trying to run superFreq using `rna` mode. Now to avoid wget error, I have downloaded the following files.
```
 mm10exons.bed  mm10exons.named.bed  mm10exons.named.dn.bed  mm10exons.named.dn.named.bed
```
then copied these files to individual directories (Individual's name comes from metafile) and resource directory. 


**By looking at the error**, looks like it can find the capture region files and there is some issue with the data loading/ parsing. I was wondering what is the issue and in which file, 

One possibility, I can think of about the chromosome naming. In my case, chromosome names are in `1, 2 ...` format (not in `chr1, chr2, ..`). Please let me know, if there is any such possibility. If yes, is there any way to check it.

**Comment by ChristofferFlensburg** [comment]
You're right that the file exists, and the script does check that before reading in. Could you try to just run 

```
bsFile = "mm10exons.named.dn.bed"
test = read.table(bsFile, fill = T, quote = "")
head(test)
```
and see if it throws the same error?
Maybe look at the file and see if it is indeed empty? Maybe the error message is actually somewhat informative, and the file is actually empty?? :D
The error is from base `read.table()`, so it's kindof that method that could be more informative about which file it's reading from. I should probably add the file path to the log entry just before though, error or not.

SuperFreq internally converts all data to `1, 2, ..` by removing `chr`, so that shouldn't be the problem.

**Comment by arpanda** [comment]
Somehow, one of those files has issue in my end. I have fixed that and its working fine. Thank you.
