### ISSUE TITLE
Successfully assigned alignments 0 error

### ISSUE THREAD

**Issue by maheshworpaudel5001** [ChristofferFlensburg/superFreq#99]
Hello Christoffer,

I have been trying to run superFreq with instructions in the manual. I have all the necessary input files and they are also setup in the necessary format. However, I have been running into a problem where the program itself does some alignment (I guess looking at the output) on already pre-aligned  bam files and complains about 0 normal counts. A part of the output looks like the following:
<img width="727" alt="Screenshot 2023-03-15 at 8 49 00 PM" src="https://user-images.githubusercontent.com/69530478/225480698-c2695418-0a71-47be-9471-45514dc4c2ae.png">

Because of the counts being 0, my fCsExon.Rdata is empty which in turn does not generate the plots required. I am also not sure what are the all the output files the run should produce. 

Anyway, the 0 count thing also happens for the normal samples I provide in the myreferencenormals directory. 

I seriously need help on this.

**Comment by ChristofferFlensburg** [comment]
This is the read count step, using rsubread, and is intended and needed for copy number calling.
The read counts of 0 are a problem, but not clear why that happened. Maybe you got some informative error messages?

In general, make sure everything is up to date (R, superFreq and dependencies), and check that your bam files, index and fasta are available, healthy and readable.

**Comment by maheshworpaudel5001** [comment]
[slurm-2876413.txt](https://github.com/ChristofferFlensburg/superFreq/files/10994848/slurm-2876413.txt)

Here is the full output of my run. I do not understand why the program writes the normal bam files of the reference normals directory twice in succession. I have checked all the input files, they look intact.

**Comment by ChristofferFlensburg** [comment]
SuperFreq doesn't write any bam files.

0 counts are almost always because the bam and or bam index files are not readable from your job submission. If you want to work on it from the R side, start by updating R and all the packages, but I don't think this is a superFreq error.

**Comment by maheshworpaudel5001** [comment]
That was error on my part. I had messed up reference genome. I downloaded it using command: bwa.kit/run-gen-ref hs38DH which is recommended by the bwa.kit manual for GRCh38 mapping. However, this command does not download correct data but only downloads ALT CTGs.
